<?php
/**
 * @file
 * Implementes the airing grid functionality 
 */

/**
 * Implements hook_menu()
 */
function cm_airing_grid_menu() {
  $items['admin/manage/scheduling'] = array(
    'title' => 'Scheduling',
    'description' => 'Manage Airing Grid',
    'page callback' => 'cm_airing_grid_admin_page',
    'access arguments' => array('view airing grid'),
  	'file' => 'includes/display.inc',
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Implements hook_admin_paths_alter().
 */
function cm_airing_grid_admin_paths_alter(&$paths) {
  $paths['admin/manage/scheduling'] = FALSE;
  $paths['admin/manage/scheduling/*'] = FALSE;
  $paths['admin/manage/scheduling/*/*'] = FALSE;
  $paths['admin/manage/scheduling/*/*/*'] = FALSE;
  $paths['admin/manage/scheduling/*/*/*/*'] = FALSE;
  $paths['admin/manage/scheduling/*/*/*/*/*'] = FALSE;
}

/**
 * Implements hook_permission()
 */
function cm_airing_grid_permission() {
	return array(
			'view airing grid' => array(
					'title' => t('View Airing Grid'),
			),
	);
}

/**
 * Menu callback calls main dispaly function includes/display.inc::cm_airing_grid_show_grid()
 */
function cm_airing_grid_admin_page($channel = null, $day = null, $start_hour = null, $airing_id = null, $grid_mode = "show_all") {

  module_load_include('inc', 'cm_airing_grid', 'includes/taxonomy_util');
  module_load_include('inc', 'cm_airing_grid', 'includes/date_util');
  module_load_include('inc', 'cm_airing_grid', 'includes/form');
  module_load_include('inc', 'cm_airing_grid', 'includes/misc');
  module_load_include('inc', 'cm_airing_grid', 'includes/query');
  module_load_include('inc', 'cm_airing_grid', 'includes/style_util');
	
  // cm_airing_grid_show_grid in display.inc
  $output = cm_airing_grid_show_grid($channel, $day, $start_hour, $airing_id, $grid_mode);

  return $output;
}

/**
 * Implements hook_help().
 */
function cm_airing_grid_help($path, $arg) {
  switch ($path) {
    case 'admin/help#cm_airing_grid':
	  return "<p>" . t('View the airings grid at admin/manage/scheduling') . "</p>";
  }
}

/**
 * Implements hook_field_attach_form().
 */ 
function cm_airing_grid_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {

  if ($entity_type != 'airing') {
  	return;	 
  } 
  
  if (!$langcode) {
  	$langcode = 'und';
  }

  // set default date 
  if (arg(2) && arg(2) != 'edit') {
    $form['field_airing_date'][$langcode][0]['#default_value']['value'] = arg(2);
    $form['field_airing_date'][$langcode][0]['#default_value']['value2'] = arg(2)+60*60;
  } else {
    if ($form['field_airing_date'][$langcode][0]['#date_timezone'] != 'UTC') { 
      $form['field_airing_date'][$langcode][0]['#date_items']['timezone'] = 'UTC';
      $form['field_airing_date'][$langcode][0]['#date_timezone'] = 'UTC';
    } 
  } 
  
  return $form;
}

/**
 * A modal login callback.
 */
function cm_airing_grid_add($js = NULL, $time = NULL, $channel = NULL, $type = NULL) {
  
  if (!$js) {
    return cm_airing_form(); 
  }  
  
  ctools_include('modal');
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  
  $airing = entity_create('airing', array('type' => 'airing'));
  
  $form_state = array(  
      'ajax' => TRUE,
      'title' => t('Add Airing'),
      'build_info' => array('args' => $airing),
      
  ); 

//  $output = cm_airing_form();
 
  $output = ctools_modal_form_wrapper('cm_airing_form', $form_state);

  if (!empty($form_state['executed'])) {
    // We'll just overwrite the form output if it was successful.
    $output = array();
    $output[] = ctools_modal_command_dismiss(t('Success!'));
    // If you want to leave a message and links:
    //$output[] = ctools_modal_command_display(t('Login Success'), '<div class="modal-message">Login successful.
    //    <a href="/modal/nojs/test">Go back</a>.</div>');
  }
  print ajax_render(cm_airing_form());
  exit;
}

function cm_airing_grid_page() {

  ctools_include('ajax');
  ctools_include('modal');
  ctools_modal_add_js();

  $custom_style = array(
      'mnn-airing-modal-style' => array(
          'modalSize' => array(
              'type' => 'fixed',
              'width' => 800,
              'height' => 600,
          ),
          'animation' => 'fadeIn',
      ),
  );
  drupal_add_js($custom_style, 'setting');

  //  $output = ctools_modal_text_button(t('Click right here'), 'simple_ass_modal/nojs/test/form', t('Pop me up'));
  $output = ctools_modal_text_button(t('Click Here'), 'airing/add/ajax',
      t('Pop me up'), 'ctools-modal-mnn-airing-modal-style');
  $output .= '<div id="modal-message">&nbsp</div>';
  ctools_include('plugins');
  return $output;
}

