<?php
/**
 * @file
 * Code for the CM Project Picker feature.
 */

include_once 'cm_project_picker.features.inc';

define('CM_PROJECT_PICKER_VIEW', 'project_picker');
define('CM_PROJECT_PICKER_SIMPLE', 'simple');

define('CM_PROJECT_PICKER_RAW', 'admin/project-picker/raw');
define('CM_PROJECT_PICKER_PAGE', 'admin/project-picker');

define('CM_PROJECT_ID_QUERY_ARGUMENT_NAME','gid');

define('CM_PROJECT_PICKET_QUERY_ARGUMENT_SESSION_VARIABLE', 'cmpp_query_args');



/**                                                                            
 * Implements hook_init().             
 */
function cm_project_picker_init() {
  drupal_add_css(drupal_get_path('module', 'cm_project_picker') .
                 '/cm_project_picker.css');
}


/**
 * Implementation of hook_menu().
 */
function cm_project_picker_menu() {
  $items = array();

  if (module_exists('cm_show')) {
    $items['admin/project-picker/show'] = array(
      'title' => 'Pick Project for adding a Show',
      'description' => 'Provides the Project Picker for adding a Show.',
      'page callback' => 'cm_project_picker_callback',
      'page arguments' => array(2),
      'access arguments' => array('access content'),  
    );
  }  
  if (module_exists('cm_airing')) {
    $items['admin/project-picker/airing'] = array(
      'title' => 'Pick a Project for adding an Airing',
      'description' => 'Provides the Project Picker for adding an Airing.',
      'page callback' => 'cm_project_picker_callback',
      'page arguments' => array(2),
      'access arguments' => array('access content'),
    );
  }
  if (module_exists('reservations')) {
    $items['admin/project-picker/reservation'] = array(
      'title' => 'Pick a Project for adding a Reservation',
      'description' =>'Provides the Project Picker for adding a Reservation.',
      'page callback' => 'cm_project_picker_callback',
      'page arguments' => array(2),
      'access arguments' => array('access content'),
    );
  }
  
  return $items;

}

function cm_project_picker_callback($type = NULL) {
  //TODO FIGURE OUT A WAY TO NON HARDCODE THIS
  $add_content_links = 
    array('show'=>'node/add/cm-show',
	  'reservation'=>'node/add/reservations-reservation',
	  'airing'=>'airing/add');

  $view = views_get_view(CM_PROJECT_PICKER_VIEW);
  $view->set_arguments(array($type));
  $output = $view->execute_display(CM_PROJECT_PICKER_SIMPLE);
  $results = $view->result;

  if (count($results) == 1) {
    drupal_goto($add_content_links[$type], 
    		array('query'=>array(CM_PROJECT_ID_QUERY_ARGUMENT_NAME=>
				     $results[0]->nid)));
  }
  if (count($results) > 1) {
    $entered_filter_data = FALSE;
    foreach($view->exposed_raw_input as $key=>$value) {
      if (isset($value) and $value) {
	$entered_filter_data = TRUE;
	break;
      }
    }
    if (!$entered_filter_data) {
      //we didn't enter data, so don't show the results, only the filters
      $output = "<div class='cm-box'>".$view->exposed_widgets."</div>";
    }
  }

  //this changes the form action to the page we are manually loading view on
  $output = cm_project_picker_change_form_action($output, $type);
  return $output;
}

function cm_project_picker_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'cm_show_node_form') {
    $nid = $form['nid']['#value'];
    $project_id = filter_input(INPUT_GET, CM_PROJECT_ID_QUERY_ARGUMENT_NAME);
    $project = node_load($project_id);
    if (!$project && !isset($nid)) {
      drupal_goto("admin/project-picker/show");
    }
  }						
  if ($form_id == 'cm_airing_form') {
    $project_id = filter_input(INPUT_GET, CM_PROJECT_ID_QUERY_ARGUMENT_NAME);
    $project = node_load($project_id);
    if (!$project && !$form['#entity']->airing_id) {
      $_SESSION[CM_PROJECT_PICKET_QUERY_ARGUMENT_SESSION_VARIABLE] =
	filter_input_array(INPUT_GET);
      drupal_goto("admin/project-picker/airing");
    }
    if (!isset($project_id)) {
      $project_id = $form['#entity']->field_airing_project_ref[LANGUAGE_NONE];
      $project_id = $project_id[0]['target_id'];
    }

    $project = node_load($project_id);

    $form['field_airing_project_ref'][LANGUAGE_NONE][0]['target_id']
      ['#value'] = $project->title." (".$project->nid.")";
    $form['field_airing_project_ref']['#type'] = "hidden";

    $form['cm_project_picker_title'] = 
      array('#markup' => 
	    "<div class='cm-box'><h2>Project</h2><big><strong>".
	    l($project->title, "node/".$project->nid).
	    "</big></strong><br/><br/></div>",
	    '#weight' => -100);
    
  }
}

function cm_project_picker_change_form_action($data, $type) {
  $old_action = 'action="/'.CM_PROJECT_PICKER_RAW;
  $new_action = 'action="/'.CM_PROJECT_PICKER_PAGE;
  $data = str_replace($old_action, $new_action, $data);
  return $data;
}
