<?php
/**
 * @file
 * Code for the MNN User Page.
 */

/**
 * Implements hook_init().
 */
function mnn_user_page_init() {
  drupal_add_css(drupal_get_path('module', 'mnn_user_page') . 
		 '/mnn_user_page.css');
}

function mnn_user_page_user_view_alter(&$build) {
  if (user_access('access CiviCRM')) {
    $build['urls']['#markup'] = "<h3> CiviCRM Links</h3>".
      $build['urls']['#markup'];
  }
  else {
    unset($build['Verification Info']);
    $value = $build['name_and_address']['name_and_address']['#value'];
    $markup = $build['name_and_address']['name_and_address']['#markup'];
    $search = '<span class="user-page-link" id="user-page-profile-Nam" ><span class="user-page-bullet">&raquo;</span> <a href="/user/';
       
    $index = strrpos($value, $search);
    $value = substr($value, 0, ($index)); 
    
    $index = strrpos($markup, $search);
    $markup = substr($markup, 0, ($index)); 

    $new = t("Please notify Media Education staff if you have changed address, or if this ".
	     "information is out of date: 212-757-2670 x 312 or education@mnn.org");

    $value .= "<br/>" . $new;
    $markup .= "<br/>" . $new;
    
    $build['name_and_address']['name_and_address']['#value'] = $value;
    $build['name_and_address']['name_and_address']['#markup'] = $markup;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mnn_user_page_form_alter(&$form, &$form_state, $form_id) {  
  if ($form_id == 'document_node_form') {
    $uid = arg(3);
    $user = user_load($uid);
    if ($user) {
      $form['field_user'][LANGUAGE_NONE][0]['uid']['#default_value'] = $uid;
    }
  }
  if ($form_id == 'user_profile_form' && !user_access('administer users') ) {
    unset($form['picture']);
    unset($form['field_suspension_notes']);
    unset($form['contact']);
  }
}

function mnn_user_page_menu_alter(&$items) { 
  $items['user/%user/edit']['title'] = t("Change Email/Password");
  $items['user/%user/view']['title'] = t("User Account");
  $items['user/%user_category/edit/Name and Address']['access callback'] = 
    'mnn_user_page_edit_link_access';
  $items['user/%user_category/edit/account']['access callback'] = 
    'mnn_user_page_edit_link_access';
}

/**
 * Callback to disallow access for the anonymous user.
 */
function mnn_user_page_edit_link_access(){
  return user_access('administer users');
}