<?php
/**
 * @file
 * Code for the VOD Feed feature.
 */

include_once('cm_vod_feed.features.inc');

/**
 * Implements hook_init().
 */
function cm_vod_feed_init() {
  drupal_add_css(drupal_get_path('module', 'cm_vod_feed') . '/cm_vod_feed.css');
  //drupal_add_js(drupal_get_path('module', 'cm_vod_feed') . '/cm_vod_feed.js');
}

/**
 * Implements hook_menu().
 */
function cm_vod_feed_menu() {

  $items['node/%node/vods'] = array(
    'title' => 'Imported Items',
    'description' => 'Takes a node object of a vod_feed and returns the vod items imported',
    'page arguments' => array(1),
    'page callback' => 'cm_vod_feed_grid',
    'access callback' => 'cm_vod_feed_display_tab',
    'access arguments' => array(1),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * controls which content types the Imported Items menu tab is displayed on
 */
function cm_vod_feed_display_tab($node) {
  return ($node->type == 'cm_vod_feed');
}

/**
 * renders view with nid as argument
 */
function cm_vod_feed_grid($node) {

  $args = array($node->nid);
  $view = views_get_view('cm_vod_feed_items');
  $view->override_url = 'node/' . $node->nid . '/vods';
  $output = $view->execute_display('default', $args);

  return $output;
}


// SEE http://www.metachunk.com/blog/adding-module-path-drupal-7-theme-registry
// These function essentially trick Drupal into thinking this module is also a theme
// where tpls can be found

/**
* Implementation of hook_registry_alter
*/
function cm_vod_feed_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'cm_vod_feed');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _cm_vod_feed_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }          
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
*/
function _cm_vod_feed_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}