<?php

/**
 * @file
 * cm_show_printable_contract functions
 */

/**
 * Implements hook_menu().
 */
function cm_show_printable_contract_menu() {

  $items['node/%node/show/contract'] = array(
    'title' => 'Contract',
    'description' => 'Takes a node object and returns a printable contract',
    'page arguments' => array(1),
    'page callback' => 'cm_show_printable_contract',
    'access callback' => 'cm_show_printable_contract_content_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );



  // Standard Administration settings.
  $items['admin/config/communitymedia/show-contract'] = array(
    'title' => 'Show Printable Contract',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cm_show_printable_contract_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('access administration pages'),
    'description' => 'Configure settings for Show\'s Printable Contract.',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function cm_show_printable_contract_permission() {
  return array(
   'view show contract' => array(
      'title' => '<em class="placeholder">Show</em>: View Contract',
      'description' => t('Allows users to access the Printable Contract tab added to Show nodes.'))
  );
}

/**
 * controls which users see the Printable Contract tab and the contract
 */
function cm_show_printable_contract_content_access($node) {
  return (user_access('view show contract') && $node->type == 'cm_show');
}

/**
 * Implements hook_theme().
 */
function cm_show_printable_contract_theme() {

  return array(
    'cm_show_printable_contract' => array(
      'template' => 'cm_show-printable-contract',
      'variables' => array('node' => NULL),
    ),
  );
}

/**
 * Builds the admininstration settings form.
 */
function cm_show_printable_contract_admin_settings($form, &$form_state) {

  $form['cm_show_contract_header'] = array(
    '#type' => 'textarea',
    '#title' => t('Contract header'),
    '#rows' => 10,
    '#default_value' => variable_get('cm_show_contract_header', ''),
    '#description' => t('Header portion of printable contract.  Allows HTML.'),
  );

  $form['cm_show_contract_boilerplate'] = array(
    '#type' => 'textarea',
    '#title' => t('Contract boilerplate'),
    '#rows' => 10,
    '#default_value' => variable_get('cm_show_contract_boilerplate', ''),
    '#description' => t('Legalese that makes the contract legally binding.'),
  );

  $form['cm_show_contract_footer'] = array(
    '#type' => 'textarea',
    '#title' => t('Contract footer'),
    '#rows' => 10,
    '#default_value' => variable_get('cm_show_contract_footer', ''),
    '#description' => t('Footer portion of printable contract. Normally includes signature lines. HTML allowed.'),
  );

  if (module_exists('token')) {
    $form['token_help'] = array(
      '#title' => t('Replacement patterns'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );

    // TODO Please change this theme call to use an associative array for the $variables parameter.
    $form['token_help']['help'] = array(
      '#value' => theme('token_help', 'node'),
    );
  }

  return system_settings_form($form);
}

/**
 * Returns contract with only the settings in cm_show-printable-contract.tpl
 */
function cm_show_printable_contract($node) {
  print theme('cm_show_printable_contract', array('node' => $node));
}


/**
 * Variables sent to cm_show-printable-contract.tpl
 */
function cm_show_preprocess_cm_show_printable_contract(&$variables) {

  $node = $variables['node'];
  $user     = user_load($node->uid);
  
  $username = $user->name;
  $email    = $user->mail;
  if (module_exists('civicrm')) {

    civicrm_initialize(TRUE);
    global $civicrm_root;

    require_once $civicrm_root . '/CRM/Core/BAO/UFMatch.php';
    $userID = CRM_Core_BAO_UFMatch::getContactId( $user->uid );

    $cg = array('contact_id' => $userID);
    include_once $civicrm_root . '/api/v2/Contact.php';
    $ob = civicrm_contact_get($cg);
    //update username
    $username = $ob[$userID]['display_name'];
    $phone = $ob[$userID]['phone'];
  }


  $variables['username'] = $username;
  $variables['email'] = $email;
  $variables['phone'] = $phone;

}


