<?php

/**
 * @file
 * cma_reservation_cache 
 */

//CHART FILTERS
define('CMA_RESERVATION_CACHE_FIRST_DAY', 'fd');
define('CMA_RESERVATION_CACHE_LAST_DAY', 'ld');
define('CMA_RESERVATION_CACHE_BEGIN_HOUR', 'bh');
define('CMA_RESERVATION_CACHE_END_HOUR', 'eh');
define('CMA_RESERVATION_CACHE_DOW', 'dow');
define('CMA_RESERVATION_CACHE_SEPARATE_CHARTS', 'sc');
define('CMA_RESERVATION_CACHE_INVENTORY', 'i');
define('CMA_RESERVATION_CACHE_BUCKET_CATEGORY', 'bc');
define('CMA_RESERVATION_CACHE_ITEM_TYPE', 'it');
define('CMA_RESERVATION_CACHE_ITEM_NID', 'in');
define('CMA_RESERVATION_CACHE_MODE', 'm');

//NAMES OF CACHES IN OPTIONS ARRAY IN THE VARIABLE TABLE, THE FIRST IS THE
//ARRAY THAT HOLDS ALL THE OPTIONS
define('CMA_RESERVATION_CACHE_CHART_OPTIONS',
       'cma_reservation_cache_chart_options');
define('CMA_RESERVATION_CACHE_INVENTORY_OPTIONS',
       'cma_reservation_cache_inventory_options');
define('CMA_RESERVATION_CACHE_CATEGORY_OPTIONS',
       'cma_reservation_cache_category_options');
define('CMA_RESERVATION_CACHE_CONTENT_TYPE_OPTIONS',
       'cma_reservation_cache_content_type_options');
define('CMA_RESERVATION_CACHE_RESOURCE_OPTIONS',
       'cma_reservation_cache_resource_options');



/**
 * Implements hook_init().
 */
function cma_reservation_cache_init() {
  drupal_add_css(drupal_get_path('module', 'cma_reservation_cache') . 
		 '/cma_reservation_cache.css');

  module_load_include('inc', 'cma_reservation_cache', 'inc/chart');
  module_load_include('inc', 'cma_reservation_cache', 'inc/misc');
  module_load_include('inc', 'cma_reservation_cache', 'inc/read_cache');
  module_load_include('inc', 'cma_reservation_cache', 'inc/report');
  module_load_include('inc', 'cma_reservation_cache', 'inc/settings');
  module_load_include('inc', 'cma_reservation_cache', 'inc/write_cache');
}
/**
 * Implements hook_permission().
 */
function cma_reservation_cache_permission() {
}


/**
 * Implements hook_menu().
 */
function cma_reservation_cache_menu() {
  // Standard Administration settings.
    $items['admin/config/cma_reservation_cache'] =
    array(
	  'title' => 'CMA Reservation Cache',
	  'description' => 'Configure settings for CMA Reservation Cache.',
	  'page callback' => 'cma_reservation_cache_settings_home',
	  'access arguments' => array('administer reservations'),
	  'type' => MENU_NORMAL_ITEM,
	  );
  $items['admin/config/cma_reservation_cache/default'] =
    array(
	  'title' => 'Cache Settings',
	  'description' => 'Configure settings for CMA Reservation Cache.',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('cma_reservation_cache_settings_form'),
	  'access arguments' => array('administer reservations'),
	  );
  $items['admin/config/cma_reservation_cache/default'] =
    array(
	  'title' => 'Default Settings',
	  'description' => 'Configure settings for CMA Reservation Cache.',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('cma_reservation_cache_settings_form'),
	  'access arguments' => array('administer reservations'),
	  );    
  // report and log views
  $items['admin/reports/cma_reservation_cache'] =
    array(
	  'title' => 'Reservation Cache Report and Tools',
	  'description' => t('View Cache Report and reload caches.'),
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('cma_reservation_cache_report'),
	  'access arguments' => array('administer reservations'),
	  'type' => MENU_NORMAL_ITEM,
	  );

    // report and log views
  $items['reservations/chart'] =
    array(
	  'title' => 'Reservation Chart',
	  'description'=>t('View chart of reservable items and reservations.'),
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('cma_reservation_cache_chart_form'),
	  'access arguments' => array('access content'),
	  'type' => MENU_NORMAL_ITEM,
	  );

  return $items;
}



    

