<?php 

/**
 * @file
 * Adds a MediaRSS feed processor to the Feeds module.
 */

/**
 * Implements ctools_plugin_api().
 */

function feeds_mediarss_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_mediarss_feeds_plugins() {
  $info = array();
  $info['FeedsMediaRSSParser'] = array(
    'name' => 'MediaRSS parser',
    'description' => 'Parse MediaRSS feeds.',
    'help' => 'Use PHP SimpleXML parser to parse MediaRSS feeds.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsMediaRSSParser',
      'file' => 'FeedsMediaRSSParser.inc',
      'path' => drupal_get_path('module', 'feeds_mediarss'),
    ),
  );
  return $info;
}
