<?php

/**
 * @file
 * Install file for Internet Archive Module.
 */

/**
 * Check that the curl extension exists for PHP.
 */
function internet_archive_requirements($phase) {
  $requirements = array();
  // Ensure translations don't break at install time
  $t = get_t();

  if ($phase == 'runtime') {
    // Check for CURL
    $curl = extension_loaded('curl');
    $description =
      $t('Internet Archive API requires PHP to have the <a href="@url">' .
	 'Curl libraries</a>. If your version of PHP does not have it, ' .
	 'check with your system administrator.',
	 array('@url' => 'http://php.net/manual/en/book.curl.php'));

    $requirements['internet_archive'] =
      array(
	    'title' => $t('PHP Curl Support'),
	    'description' => $description,
	    'value' => $curl ? $t('Enabled') : t('Not found'),
	    'severity' => $curl ? REQUIREMENT_OK : REQUIREMENT_ERROR,
	    );
  }

  return $requirements;
}

/**
 * Implements hook_schema().
 */
function internet_archive_schema() {
  $schema['internet_archive'] = array(
    'description' =>
    'Holds file data for files stored at the internet archive.',
    'fields' => array(
      'tid' => array(
        'type' => 'serial',
        'description' => 'Transfer ID',
      ),
      'nid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'in_path' => array(
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
        'description' => 'Original file path',
      ),
      'file_name' => array(
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
        'description' => 'File Name',
      ),
      'file_size' => array(
        'type' => 'int',
        'size' => 'big',
        'not null' => TRUE,
        'description' => 'File Size',
      ),
      'field_name' => array(
        'type' => 'varchar',
	'length' => 255,
	'default' => '',
	'description' => 'The field name of the Drupal Entity',
      ),
      'file_location' => array(
        'type' => 'varchar',
	'length' => 255,
	'default' => '',
	'description' => 'The field name of the Drupal Entity',
      ),
      'archive_url' => array(
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
        'description' => 'Internet Archive Path',
      ),
      'md5' => array(
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
        'description' => 'MD5 hash of file',
      ),
      'item' => array(
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
        'description' => 'Internet Archive Item / Bucket',
      ),
      'status' => array(
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
        'description' => 'Internet Archive Transfer Status',
      ),
      'derivatives' => array(
        'type' => 'text',
        'not null' => FALSE,
        'size' => 'big',
        'serialize' => TRUE,
        'description' => 'All available derivative information',
      ),
      'attempts' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'transfer_initiated' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Transfer start date as unix timestamp',
      ),
      'date' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Transfer finish date as unix timestamp',
      ),
    ),
    'indexes' => array(
      'tid' => array('tid'),
    ),
    'primary key' => array('in_path'),
  );

  $schema['internet_archive_log'] = array(
    'description' => 'Holds log entries for file transfer actions',
    'fields' => array(
      'lid' => array(
        'type' => 'serial',
        'description' => 'Log ID',
      ),
      'tid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'message' => array(
        'type' => 'text',
        'not null' => FALSE,
        'size' => 'big',
        'serialize' => TRUE,
        'description' => 'Message',
      ),
      'message_data' => array(
        'type' => 'text',
        'not null' => FALSE,
        'size' => 'big',
        'serialize' => TRUE,
        'description' => 'Message data',
      ),
      'type' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'date' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Log entry date',
      ),
    ),
    'indexes' => array(
      'lid' => array('lid'),
    ),
    'primary key' => array('lid'),
  );

  // cache schema
  $schema['cache_internet_archive'] = drupal_get_schema_unprocessed('system',
								    'cache');
  $schema['cache_internet_archive']['description'] =
    'Cache table for the Internet Archive module to store transfer data';

  return $schema;
}
