<?php
/**
 * @file
 * Provides integration between Drupal files and Archive.org.
 *
 */

/**
 * File status in regards to Archive.org
 */
define('ARCHIVE_QUEUED', 'queued');
define('ARCHIVE_TRANSFERRING', 'transferring');
define('ARCHIVE_TRANSFERRED', 'transferred');
define('ARCHIVE_VALIDATED', 'validated');
define('ARCHIVE_DERIVED', 'derived');
define('ARCHIVE_DELETED', 'deleted');
define('ARCHIVE_FAILED', 'failed');


/**
 * Log table status levels
 */
define('ARCHIVE_LOG_ERROR', 1);
define('ARCHIVE_LOG_WARNING', 2);
define('ARCHIVE_LOG_NOTICE', 3);

/**
 * Implements hook_permission().
 */
function internet_archive_permission() {
  return array(
    'administer internet_archive' => array(
      'title' => t('administer internet_archive'),
      'description' =>
      t('TODO Add a description for \'administer internet_archive\''),
    ),
    'access all internet_archive node tabs' => array(
      'title' => t('access all internet_archive node tabs'),
      'description' =>
      t("TODO Add a description for 'access all internet_archive node tabs'"),
    ),
    'access own internet_archive node tabs' => array(
      'title' => t('access own internet_archive node tabs'),
      'description' =>
      t("TODO Add a description for 'access own internet_archive node tabs'"),
    ),
    'update all internet_archive metadata' => array(
      'title' => t('update all internet_archive metadata'),
      'description' =>
      t('TODO Add a description for \'update all internet_archive metadata\''),
    ),
    'update own internet_archive metadata' => array(
      'title' => t('update own internet_archive metadata'),
      'description' =>
      t('TODO Add a description for \'update own internet_archive metadata\''),
    ),
    'access internet_archive logs' => array(
      'title' => t('access internet_archive logs'),
      'description' =>
      t('TODO Add a description for \'access internet_archive logs\''),
    ),
    'delete all internet_archive files' => array(
      'title' => t('delete all internet_archive files'),
      'description' =>
      t('TODO Add a description for \'delete all internet_archive files\''),
    ),
    'delete own internet_archive files' => array(
      'title' => t('delete own internet_archive files'),
      'description' =>
      t('TODO Add a description for \'delete own internet_archive files\''),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function internet_archive_menu() {
  // Main settings pages
  $items['admin/config/internet_archive'] =
    array(
	  'title' => 'Internet Archive',
	  'description' =>
	  t('Configure how files are transferred to Archive.org'),
	  'page callback' => 'internet_archive_settings_home',
	  'access arguments' => array('administer internet_archive'),
	  'type' => MENU_NORMAL_ITEM,
	  );
  $items['admin/config/internet_archive/default'] =
    array(
	  'title' => 'Default Settings',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('internet_archive_admin_form'),
	  'access arguments' => array('administer internet_archive'),
	  'weight' => -3,
	  );

    $items['admin/config/internet_archive/queue'] =
      array(
	    'title' => 'Queue Settings',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('internet_archive_queue_settings_form'),
	    'access arguments' => array('administer internet_archive'),
	    'file' => 'includes/internet_archive_queue.inc',
	    'weight' => 0,
	    );
    
    // report and log views
    $items['admin/reports/internet_archive'] =
      array(
	    'title' => 'Internet Archive Log',
	    'description' => t('View the file transfer log and statistics'),
	    'page callback' => 'internet_archive_reports_home',
	    'access arguments' => array('administer internet_archive'),
	    'type' => MENU_NORMAL_ITEM,
	    );
    $items['admin/reports/internet_archive/default'] =
      array(
	    'title' => 'Uploads',
	    'page callback' => 'internet_archive_reports_log',
	    'access arguments' => array('administer internet_archive'),
	    'type' => MENU_DEFAULT_LOCAL_TASK,
	    'weight' => -3,
	    );
  $items['admin/reports/internet_archive/log'] =
    array(
	  'title' => 'System Messages',
	  'page callback' => 'internet_archive_reports_system_messages',
	  'access arguments' => array('administer internet_archive'),
	  'type' => MENU_LOCAL_TASK,
	  'weight' => 55,
	  );
  $items['admin/reports/internet_archive/stats'] =
    array(
	  'title' => 'Statistics',
	  'page callback' => 'internet_archive_reports_statistics',
	  'access arguments' => array('administer internet_archive'),
	  'type' => MENU_LOCAL_TASK,
	  'weight' => 50,
	  );

  $items['admin/structure/internet_archive'] =
    array(
	  'title' => 'Internet Archive Queues',
	  'description' => t('View file transfer queues'),
	  'page callback' => 'internet_archive_queues_home',
	  'access arguments' => array('administer internet_archive'),
	  'type' => MENU_NORMAL_ITEM,
	  );
  $items['admin/structure/internet_archive/default'] =
    array(
	  'title' => 'Upload Queue',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('internet_archive_queue_add_remove_form'),
	  'access arguments' => array('administer internet_archive'),
	  'file' => 'includes/internet_archive_queue.inc',
	  'type' => MENU_DEFAULT_LOCAL_TASK,
	  'weight' => -1,
	  );
  //manual file and node based commands
  $items['internet_archive/%/transfer'] =
    array(
	  'title' => 'Confirm File Transfer to Archive.org',
	  'page callback' => 'drupal_get_form',
	  'access arguments' => array('administer internet_archive'),
	  'page arguments' => array('internet_archive_transfer_confirm', 1),
	  );
  $items['node/%node/ia'] =
    array(
	  'title' => 'Internet Archive',
	  'page callback' => internet_archive_node_status,
	  'page arguments' => array(1),
	  'access callback' => internet_archive_tab_permission,
	  'access arguments' => array(1),
	  'type' => MENU_LOCAL_TASK,
	  'weight' => 10,
	  );
  $items['node/%node/ia/update-metadata'] =
    array(
	  'title' => 'Internet Archive Metadata Update',
	  'page callback' => internet_archive_update_node_metadata,
	  'page arguments' => array(1),
	  'access callback' =>internet_archive_update_node_metadata_permission,
	  'access arguments' => array(1),
	  'type' => MENU_CALLBACK,
	  'weight' => 10,
  );
  $items['node/%node/ia/delete-files'] =
    array(
	  'title' => 'Internet Archive Metadata Delete',
	  'page callback' => internet_archive_delete_node_files,
	  'page arguments' => array(1, 4),
	  'access callback' => internet_archive_delete_node_files_permission,
	  'access arguments' => array(1),
	  'type' => MENU_CALLBACK,
	  'weight' => 10,
	  );
  $items['ia/log'] =
    array(
	  'title' => 'Internet Archive File Log',
	  'page callback' => internet_archive_log_view,
	  'page arguments' => array('tid', 2),
	  'access arguments' => array('access internet_archive logs'),
	  'type' => MENU_CALLBACK,
	  'weight' => 11,
	  );

  return $items;
}

/**
 * Loads the general settings form.
 *
 * @see internet_archive_admin_form()
 */
function internet_archive_settings_home() {
  return drupal_get_form('internet_archive_admin_form');
}

/**
 * Loads the general report page.
 *
 */
function internet_archive_reports_home() {
  return internet_archive_reports_log();
}

/**
 * Loads the queue page.
 *
 */
function internet_archive_queues_home() {
  module_load_include('inc', 'internet_archive', 'includes/internet_archive_queue');
  return drupal_get_form('internet_archive_queue_add_remove_form');
}

/**
 * Implements hook_node_update().
 */
function internet_archive_node_update($node) {
  dsm($node,'node');
  if (variable_get('internet_archive_update', FALSE)) {
    dsm('hi mom');
    if ($files = internet_archive_node_files($node->nid)) {
      dsm($files, 'files');
      foreach ($files as $key => $archive_data) {
	dsm($file, 'file');
	dsm($archive_data, 'ad');
        internet_archive_update_item($archive_data['in_path']);
      }
    }
  }
}

/**
 * Implements hook_field_display_alter().
 * Adds archive.org file status and manual transfer links
 * beneath relevant field displays
 */
function internet_archive_field_attach_view_alter(&$output, $context) {
  dsm('internet_archive_field_attach_view_alter');
  //grab all applicable fields
  $fields = internet_archive_fields();

  foreach ($fields as $field_name => $field_info) {
    //get the value key to reference
    switch ($field_info['type']) {
    case 'filefield':
    case 'text':
    case 'emvideo':
      $value_key = NULL;
      drupal_set_message('Only the file field type is defined at this time',
			 'warning');
      break;
    case 'file':
      $value_key = 'uri';
      break;
      
    }
    if (isset($output[$field_name]) && $output[$field_name]) {
      if ($output[$field_name]['#items'][0][$value_key]) {
	dsm($output[$field_name]['#items'], 'yo');
        $suffix =
	  internet_archive_theme_field_display($output[$field_name]['#items'],
					       $value_key);
      }
      if ($suffix) {
	$output['field_internet_archive'][0]['#suffix'] = $suffix;
      }
    }
  }
}

/**
 * Loads all fields chosen on the general settings page
 *
 * @return $fields
 *   An array of field objects.
 */
function internet_archive_fields() {
  $fields = array();
  $field_info = field_info_field_map();
  if (($field_types = variable_get('internet_archive_fields', FALSE)) &&
      variable_get('internet_archive_fields_list_display', FALSE)) {
    foreach ($field_types as $field_name => $description) {
      $fields[$field_name] = $field_info[$field_name];
    }
  }

  return $fields;
}

/**
 * Themes the additional archive.org field data provided on node view.
 * TODO: make into a real theme function
 *
 * @param $filefield
 *   A field array.
 * @param $value_key
 *   The name of the array value containing the filepath.
 *
 * @return $filefield_output
 *   A string containing formatted archive.org utility links
 */
function internet_archive_theme_field_display($field, $value_key) {
  dsm('internet_archive_theme_field_display');
  $field_transfer = '';
  $field_archived = '';
  foreach ($field as $key => $file_info) {
    if ($file_info[$value_key]) {
      dsm($file_info[$value_key], 'file info value key');
      $archive_data = internet_archive_load_data($file_info[$value_key]);
      dsm($archive_data, 'archive data');
      if ($archive_data && ($archive_data['status'] == ARCHIVE_VALIDATED ||
			    $archive_data['status'] == ARCHIVE_DERIVED)) {
        $field_archived .= l(basename($file_info[$value_key]),
			     $archive_data['archive_url']) . ' ';
	
        $url_info = parse_url($archive_data['archive_url']);
        $field_archived .= ' | ' .
	  l($archive_data['item'],
	    'https://www.archive.org/details/' .$archive_data['item']);

	$field_archived .= internet_archive_embed($archive_data['tid']);
	dsm($field_archived, 'fa');
      }
      elseif ($archive_data && ($archive_data['status'] != ARCHIVE_VALIDATED ||
				$archive_data['status'] != ARCHIVE_DERIVED)) {
        $field_transfer .= 'Currently pending transfer...';
      }
      else {
	$uri = $file_info[$value_key];

        $field_transfer .=
	  l(basename($file_info[$value_key]), 'internet_archive/' .
	    urlencode(str_replace('/', '!-!', $uri)) .
	    '/transfer', array('query' => drupal_get_destination())) . ' ';
	dsm($field_transfer, 'ft');
      }
    }
  }

  $field_output = '';
  if (isset($field_archived) && $field_archived) {
    $field_output =
      '<span class="internet-archive-files">'.
      '<span class="internet-archive-archived">Archive.org: ' .
      $field_archived . '</span>';
  }
  if ($field_archived && $field_transfer) {
    $field_output .= '<br />';
  }
  if ($field_transfer) {
    $field_output .= '<span class="internet-archive-transfer">'.
      'Transfer to Archive.org: ' . $field_transfer . '</span>';
  }

  return "<br/>".$field_output;
}

/**
 * Instantiates a new S3 class.
 *
 * @param $key
 *   A string containing an archive.org user account access key.
 * @param $skey
 *   A string containing an archive.org user account private key.
 *
 * @return $s3
 *   An s3 class provided by includes/archive.php.
 */
function internet_archive_new_s3($key = FALSE, $skey = FALSE) {
  dsm('internet_archive_new_s3');
  // If the flash video module is installed, do not require this
  require_once DRUPAL_ROOT . '/' .
    drupal_get_path('module', 'internet_archive') . '/includes/archive.php';

  // if keys are being passed in, override defaults
  // AWS access info
  if (!defined('archiveAccessKey')) {
    define('archiveAccessKey', $key ? $key :
	   variable_get('internet_archive_key', NULL));
  }
  if (!defined('archiveSecretKey')) {
    define('archiveSecretKey', $skey ? $skey :
	   variable_get('internet_archive_skey', NULL));
  }
  $s3 = new S3(archiveAccessKey, archiveSecretKey);

  return $s3;
}

/**
 * Form builder for the internet archive site settings form.
 *
 * @ingroup forms
 */
function internet_archive_admin_form($form) {
  $form['internet_archive_help'] =
    array(
	  '#value' => '<p><strong>' .
	  internet_archive_help_links('using-internet-archive', 'link') .
	  '</strong></p>',
  );

  $form['internet_archive_account'] =
    array(
	  '#type' => 'fieldset',
	  '#element_validate' => array('internet_archive_admin_validate'),
	  '#title' => 'Archive.org Account Configuration',
	  '#description' =>
	  t('Global settings for Archive.org S3 configurations.'),
  );

  $default_value =str_replace(' ','_', variable_get('site_name',t('My Site')));
  $default_value = variable_get('internet_archive_bucket', $default_value);
  
  $form['internet_archive_account']['internet_archive_bucket'] =
    array(
	  '#type' => 'textfield',
	  '#title' => t('Default Archive.org Item to store files in'),
	  '#default_value' => $default_value,
	  '#description' =>
	  t("Name of the Archive.org item that files will be placed into, ".
	    "note this has to be unique. This can be overridden by a , ".
	    "configuration but this is the default value and used to test ".
	    "your connection."),
	  '#required' => TRUE,
	  );

  $default_value =
    variable_get('internet_archive_default_server_url',
		 "http://s3.us.archive.org/");
    
  $form['internet_archive_account']['internet_archive_default_server_url'] =
    array(
	  '#type' => 'textfield',
	  '#title' => t('Archive.org S3 URL'),
	  '#default_value' => $default_value,
	  '#description' =>
	  t("URL to send to archive. You probably don't need to change this."),
	  '#required' => TRUE,
	  );
  
  $form['internet_archive_account']['internet_archive_key'] =
    array(
	  '#type' => 'textfield',
	  '#title' => t('Archive.org S3 Access Key'),
	  '#default_value' => variable_get('internet_archive_key', ""),
	  '#description' => t("You can obtain one at: ") .
	  l('http://www.archive.org/account/s3.php',
	    'http://www.archive.org/account/s3.php'),
	  '#required' => TRUE,
	  );
  
  $form['internet_archive_account']['internet_archive_skey'] =
    array(
	  '#type' => 'textfield',
	  '#title' => t('Archive.org S3 Secret Key'),
	  '#default_value' => variable_get('internet_archive_skey', ""),
	  '#description' => t("You can obtain one at: ") .
	  l('http://www.archive.org/account/s3.php',
	    'http://www.archive.org/account/s3.php'),
	  '#required' => TRUE,
	  );

  $form['internet_archive_data'] =
    array(
	  '#type' => 'fieldset',
	  '#title' => 'Basic item and metadata options',
	  '#description' =>
	  t('Basic item and metadata options. More advanced configurations '.
	    'can override these settings in a custom module via '.
	    'hook_internet_archive_metadata.'),
	  );
  
  $form['internet_archive_data']['internet_archive_update'] = array(
    '#type' => 'checkbox',
    '#title' =>
    t('Update metadata on archive.org for already transferred files when '.
      'nodes are updated?'),
    '#default_value' => variable_get('internet_archive_update', FALSE),
    '#description' =>
    t("If this option is checked, all item metadata will be resent to ".
      "archive.org when their associated nodes are updated."),
  );
  $form['internet_archive_data']['internet_archive_bucket_title'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use node title for item name when available?'),
    '#default_value' => variable_get('internet_archive_bucket_title', FALSE),
    '#description' =>
    t("This provides a simple alternative to storing files in the default ".
      "item above. Checking this box will result in all transferred files ".
      "being stored in a item/bucket based on their source node title."),
  );
  $form['internet_archive_data']['internet_archive_bucket_body'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use node body for item description when available?'),
    '#default_value' => variable_get('internet_archive_bucket_body', FALSE),
    '#description' =>
    t("If this box is checked, when a node body is available it will be sent ".
      "along as the description for the item on archive.org"),
  );

  $default_value =
    variable_get('internet_archive_collection', "test_collection");
  $description =
    t("Archive.org is broken into many collections. For initial testing ".
      "this defaults to the test collection where files are automatically ".
      "deleted after 30 days. Once you are done testing, you should change ".
      "this to an appropriate permanent collection. You can specify ".
      "multiple collections separated by commas but make sure to put them ".
      "in order of most specific to most general. Note that if you are ".
      "using the om_metadata submodule you do not need to add additional ".
      "collections like openmediaproject or community_media here as the ".
      "submodule handles that automatically") . '<br /><strong>' .
    t("Example: denveropenmedia") . '</strong>';

  $form['internet_archive_data']['internet_archive_collection'] = array(
    '#type' => 'textfield',
    '#title' => t('Default collection to store files to'),
    '#default_value' => $default_value,
    '#description' => $description,
  );
  $form['internet_archive_data']['internet_archive_derivatives'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of expected derivatives'),
    '#default_value' => variable_get('internet_archive_derivatives', 3),
    '#description' =>
    t("For a video file, archive.org typically creates 3 derivatives in ".
      "addition to the original file (GIF, OGG, MP4). For audio, there is ".
      "typically 1 derivation (OGG). The module uses this value in order to ".
      "discern when your transfer has finished the derivation process, once ".
      "the number of derivatives reported is equal to or greater than the ".
      "value entered here, the module will update the file status to ".
      "derived and it will start displaying in embeds."),
  );

  $form['internet_archive_data']['internet_archive_mediatype'] = array(
    '#type' => 'select',
    '#title' => t('Default filetype to store files as'),
    '#default_value' => variable_get('internet_archive_mediatype', 'movies'),
    '#options' => array(
      'audio' => 'Audio',
      'education' => 'Education',
      'image' => 'Images',
      'software' => 'Software',
      'movies' => 'Video',
    ),
    '#multiple' => FALSE,
    '#description' =>
    t("This type applies in situations where the system is not provided ".
      "with a media type from hook_internet_archive_metadata, and is not ".
      "able to defer the type from the file itself."),
  );
  

  $description = '<div>' .
    t('Select any fields below that you would like to use to transfer '.
      'files to Archive.org. File, text and embedded media fields are '.
      'supported.') . '<strong>' .
    t(' All fields selected must contain accessible path information as '.
      'their value. Any embedded media fields must be using a '.
      '<a href="http://drupal.org/project/media_video_flotsam">custom type</a>'
      .', with paths entered for the URL. In other words, don\'t expect '.
      'this module to transfer your embedded youtube videos to Archive.org.'.
      'If you are storing path data for files on a remote server, please '.
      'enable and configure the Internet Archive Remote submodule.') .
    '</strong>';
    
  $form['internet_archive']['internet_archive_field_support'] =
    array(
	  '#type' => 'fieldset',
	  '#title' => 'Field Integration',
	  '#description' => $description,
	  );

  $form['internet_archive']['internet_archive_field_support']
    ['internet_archive_fields'] =
    array(
	  '#type' => 'select',
	  '#title' => t('Include the following fields as file sources'),
	  '#default_value' => variable_get('internet_archive_fields', FALSE),
	  '#options' => internet_archive_field_select_options(),
	  '#multiple' => TRUE,
	  );

  $default_value =
    variable_get('internet_archive_fields_list_display', TRUE);
  
  $form['internet_archive']['internet_archive_field_support']
    ['internet_archive_fields_list_display'] =
    array(
	  '#type' => 'checkbox',
	  '#title' =>
	  t('Display archive.org file information when displaying '.
	    'selected fields on nodes?'),
	  '#default_value' => $default_value,
	  );

  $default_value = variable_get('internet_archive_fields_add_inline', TRUE);
  $form['internet_archive']['internet_archive_field_support']
    ['internet_archive_fields_add_inline'] =
    array(
	  '#type' => 'checkbox',
	  '#title' =>
	  t('Offer "add to Archive.org" link when displaying selected '.
	    'fields on nodes?'),
	  '#default_value' => $default_value,
	  );
  

  $form['internet_archive']['internet_archive_report_settings'] =
    array(
	  '#type' => 'fieldset',
	  '#title' => 'Report Settings',
	  '#description' => $description,
	  );

  $form['internet_archive']['internet_archive_report_settings']
    ['internet_archive_results_per_page'] =
    array(
	  '#type' => 'textfield',
	  '#title' => t('Number of results per report page'),
	  '#default_value' =>
	  variable_get('internet_archive_results_per_page', 100),
	  '#description' =>
	  t('The number of results that appear on the '.
	    'Internet Archive Log report'),
	  );

  $default_value =
    variable_get('internet_archive_show_only_errors_and_warnings', FALSE);
  
  $form['internet_archive']['internet_archive_report_settings']
    ['internet_archive_show_only_errors_and_warnings'] =
    array(
	  '#type' => 'checkbox',
	  '#title' =>
	  t('Should the "System Messages" tab on the Internet Archive Log '.
	    'show only Errors and Warnings?'),
	  '#default_value' => $default_value,
	  );
  
  $form['internet_archive']['internet_archive_debug'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Debug Mode'),
    '#default_value' => variable_get('internet_archive_debug', FALSE),
    '#description' =>
    t("Enables verbose watchdog messages for debug purposes."),
  );

  return system_settings_form($form);
}

/**
 * Loads all views indicated as file views on the general settings page.
 *
 * @return $views
 *   An array of view names.
 */
function internet_archive_file_views() {
  $all_views = views_get_all_views();

  $views = array();
  foreach ($all_views as $key => $view) {
    if ($view->base_table == 'files' || $view->base_table == 'node') {
      $views[$view->name] = $view->name;
    }
  }
  asort($views);
  return $views;
}

/**
 * Builds an array of filepaths from views chosen on the general settings page.
 *
 * @return $unarchived_files
 *   An array of filepaths.
 */
function internet_archive_harvest_filepaths_from_views() {
  dsm("internet_archive_harvest_filepaths_from_views");
  $views = variable_get('internet_archive_file_views', NULL);

  if (!$views) {
    return FALSE;
  }

  $fields = internet_archive_fields();

  $fids = array();
  foreach ($views as $view_name => $info) {
    dsm($view_name, 'view name');
    $view_files = views_get_view_result($view_name);
    
    if (count($view_files) > 0) {
      //FIND THE FIELDS THAT HAVE OUR FILE INFO
      $key_value = '';
      foreach ($fields as $field_name => $field_info) {
	foreach ($view_files[0] as $key => $info) {
	  if ("field_" . $field_name == $key) {
	    $filefield_flag = TRUE;
	    $key_value = $key;
	    break;
	  }
	}
	if ($key_value) {
	  break;
	}
      }    

      //IF WE DONT FIND A FIELD KEY TO GRAB FILE INFO THEN THIS VIEW IS
      //NOT CONFIGURED CORRECTLY
      if (!$key_value) {
	drupal_set_message("Error Code #33453 No field found for $view_name",
			   'error');
        continue;
      }

      foreach ($view_files as $key => $fileinfo) {
	dsm($fileinfo, 'fileinfo');
        if ($filefield_flag) {
	  $field = $fileinfo->{$key_value};
	  if (!$field) {
	    //THE FIELD DOES NOT EXIST, MAYBE THE FILE IS NOT SET TO DISPLAY?
	    continue;
	  }
	  $uri = $field[0]['raw']['uri'];

          $filepaths[] = $uri;
        }
        else if (file_exists($fileinfo->{$key_value})) {
	  //FIXME, HANDLE THIS CASE FOR OTHER TYPES OF FIELDS
        }
      }
      dsm($filepaths, 'filepaths');
    }
  }

  $unarchived_files = array();

  if ($filepaths) {
    foreach ($filepaths as $filepath) {
      $archive_data = internet_archive_load_data($filepath);
      if ((!$archive_data) && file_exists($filepath)) {
        $unarchived_files[] = $filepath;
      }
    }
  }

  return $unarchived_files;
}

/**
 * Implements hook_cron().
 */
function internet_archive_cron() {
  dsm("internet archive cron");

  //validate previous transfers
  internet_archive_validate_transfers();
  dsm("finished validating");
  if (variable_get('internet_archive_queue_harvest_cron', FALSE)) {
    //Add new files to queue if available
    internet_archive_harvest_files();
    dsm("finished harvesting");
  }
  
  //Check for new derivations to update.
  internet_archive_store_derivatives();
  dsm("finished deriviatives");
}

/**
 * Primary file harvest function, grabs candidates from views based on administrative
 * settings and adds them to a drupal queue for later transfer.
 */
function internet_archive_harvest_files() {
  dsm('internet_archive_harvest_files');
  //Check to see if we should authenticate
  if ($cron_user = variable_get('internet_archive_cron_user', FALSE)) {
    global $user;
    $original_user = $user;
    drupal_save_session(FALSE);
    $tmp = array();
    $users = array('name' => $cron_user);
    $array = user_load_multiple($tmp, $users);
    $user = array_shift($array);
  }
  //administrative setting for requeing stale/expired queue items
  if (variable_get('internet_archive_expired_queue', FALSE)) {
    internet_archive_harvest_expired_queued();
  }
  
  $filepaths = internet_archive_harvest_filepaths_from_views();
  dsm($filepaths, 'got filepaths');
  
  if (variable_get('internet_archive_queue_attempts', 0) > 0) {
    dsm("got queue attempts");
    $reprocess_filepaths = internet_archive_harvest_failed();
    dsm($reprocess_filepaths, 'found some reprocessed files?');
    if ($reprocess_filepaths) {
      $filepaths = array_merge($reprocess_filepaths, $filepaths);
    }
  }
  dsm($filepaths, 'filepaths after merge');
  $transfer_queue = DrupalQueue::get('internet_archive_send_file');
  dsm($transfer_queue->numberOfItems(), 'number of items');
  dsm($transfer_queue, 'tq');

  if ($filepaths) {
    foreach ($filepaths as $key => $filepath) {
      dsm($filepath, 'filepath in loop');

      if (file_exists($filepath)) {
	
	$status = internet_archive_get_status($filepath);
	dsm($status, 'status');
	if ($status != ARCHIVE_QUEUED && $status != ARCHIVE_TRANSFERRING
	    && $status != ARCHIVE_TRANSFERRED &&
	    $status != ARCHIVE_VALIDATED && $status != ARCHIVE_DERIVED) {
	  //allow other modules to make changes before file is queued
	  unset($node);
	  $node = internet_archive_get_node_from_filepath($filepath);
	  $archive_info = array(
				'nid' => $node->nid,
				'in_path' => $filepath,
				'filename' => basename($filepath),
				'filesize' =>
				internet_archive_filesize($filepath),
				'status' => ARCHIVE_QUEUED,
				);
	  internet_archive_invoke_internet_archive($archive_info, 'harvested');

	  //NEED TO MAKE SURE ITEM IS NOT ALREADY IN THE QUEUE
	  $sql = "SELECT item_id FROM {queue} WHERE data = :data";
	  $params = array(':data' => serialize($filepath));
	  $queue_id = db_query($sql, $params)->fetchField();

	  if ($queue_id) {
	    dsm("found item_id: $queue_id in the queue!");
	    continue;
	  }
	  //add the file to queue
	  $transfer_queue->createItem($filepath);
	  //update the file status to queued if this is the first attempt
	  if ($status != ARCHIVE_FAILED) {
	    $sql =
	      "INSERT into {internet_archive} " .
	      "(nid, in_path, filename, filesize, status, " .
	      "attempts, transfer_initiated, date) " .
	      "VALUES (:nid, :in_path, :filename, :size, :status, 0,0,0)";
	    dsm($archive_info, 'ai');
	    $params = array(':nid' => $archive_info['nid'],
			    ':in_path' => $archive_info['in_path'],
			    ':filename' => $archive_info['filename'],
			    ':size' => $archive_info['filesize'],
			    ':status' => $archive_info['status'],
			    );
	    dsm($params, 'params');
			    
	    db_query($sql, $params);
	  }
	  if (isset($archive_info)) {
	    unset($archive_info);
	  }
	  $archive_info = internet_archive_load_data($filepath);
	  dsm($archive_info, "archive data after fresh insert");
	  internet_archive_invoke_internet_archive($archive_info, 'queued');
	}
      }
    }
  }

  //All done, reset our user session if necessary
  if ($cron_user) {
    $user = $original_user;
  }
}

/**
 * Takes a filepath and adds it to the internet_archive_send_file queue
 *
 * @param $filepath
 *   a string containing a path to a file.
 * @return
 *   TRUE if the file is added to the queue, FALSE if not.
 */
function internet_archive_add_to_queue($filepath) {
  dsm('internet_archive_add_to_queue');
  drupal_queue_include();
  $transfer_queue = DrupalQueue::get('internet_archive_send_file');

  $status = internet_archive_get_status($filepath);
  if ($status != ARCHIVE_QUEUED && $status != ARCHIVE_TRANSFERRING && $status != ARCHIVE_TRANSFERRED) {
    //add the file to queue
    $transfer_queue->createItem($filepath);

    //update the file status to queued
    // TODO Please convert this statement to the D7 database API syntax.
    /* db_query("INSERT into {internet_archive} (in_path, status) VALUES ('%s', '%s')", $filepath, ARCHIVE_QUEUED) */
    NULL;

    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Compares current hour to the hour range set on the internet archive
 * queue settings page.
 *
 * @return
 *   TRUE if the current hour is within range, FALSE if not
 */
function internet_archive_hour_check() {
  $start_hour = variable_get('internet_archive_queue_start_time', 'none');
  if ($start_hour == 'none') {
    return TRUE;
  }

  $end_hour = variable_get('internet_archive_queue_end_time', 'none');
  $current_hour = date('G');
  $available_hours = array();

  //quick loop to find valid hours
  $set_hour = $start_hour;
  while ($set_hour != $end_hour) {
    $available_hours[] = $set_hour;
    switch ($set_hour) {
      case 23:
        $set_hour = 0;
        break;
      default:
        $set_hour++;
        break;
    }
  }

  if (in_array($current_hour, $available_hours)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Compares current day to the day/s set on the internet archive
 * queue settings page.
 *
 * @return
 *   TRUE if the current day matches one chosen, FALSE if not
 */
function internet_archive_day_check() {
  $allowed_days = variable_get('internet_archive_queue_days', 'none');
  $current_day = strtolower(date('l'));

  if (empty($allowed_days) || in_array($current_day, $allowed_days)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Checks the current archive.org status of a file
 *
 * @param $filepath
 *   String containing a relative filepath.
 * @return $status
 *   Returns current status if available, FALSE if not
 */
function internet_archive_get_status($filepath) {
  $s3_data = internet_archive_load_data($filepath);
  if ($s3_data) {
    if ($status = $s3_data['status']) {
      return $status;
    }
    else {
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
}

/**
 * Queue worker function to send files
 *
 * @param $filepath
 *   A string containing a relative filepath
 */
function internet_archive_transfer_file_worker($filepath) {
  dsm('internet_archive_transfer_file_worker');
  internet_archive_default_send($filepath);
}


/**
 * Tests the basic archive.org S3 settings from the general settings page by
 * attempting to create the default bucket at archive.org.
 *
 * @param $element
 * @param &$form_state
 *
 */
function internet_archive_admin_validate($element, &$form_state) {
  // only validate if we have both values
  if ($form_state['values']['internet_archive_key'] && $form_state['values']['internet_archive_skey']) {

    $s3 = internet_archive_new_s3($form_state['values']['internet_archive_key'], $form_state['values']['internet_archive_skey']);

    // To test the configuration credentials, we attempt to create the default bucket.
    if (! $s3->putBucket($form_state['values']['internet_archive_bucket'], NULL, $form_state['values']['internet_archive_default_perm'])) {
      form_error($element, t('Could not create your default item on the Archive servers. This most likely means that either:') . '<br />' . t('1) your default item name conflicts with one that already exists, or') . '<br />' . t('2) the access or secret key provided is incorrect.'));
    }
    else {
      drupal_set_message('Connection to Archive.org tested successfully with the credentials provided below.');
    }
  }
}




/**
 * Validatation for the internet_archive_config() form.
 * TODO: rewrite this function, leftover from mm_s3
 *
 * @param $element
 * @param &$form_state
 *
 * @ingroup forms
 */
function internet_archive_validate_action_settings($element, &$form_state) {
  // @TODO these validation steps need to be checked
  return;
  // Media Mover API will extract the corect data for this since all
  // the form elements are prefixed by media mover when the are displayed
  if ($values = internet_archive_validate_form_data_extract($element)) {
    // buckets must be lower case
    if ($values['internet_archive_bucket'] != drupal_strtolower($values['internet_archive_bucket'])) {
      form_error($element, t('Your bucket name must be lower case.'));
    }
    // alert on delete
    if ($values['internet_archive_delete_source']) {
      drupal_set_message(t('You have choosen to delete your source material.
        Please be aware that this will remove files from your server\'s file system')
      );
    }
  }
}


/**
 * Sends a file to archive.org
 * TODO: improve documentation below
 * TODO: remove the extraneous debug watchdogs
 * TODO: find a better solution to the sleep hack
 *
 * @param $config
 *   An array containing s3 parameters
 *
 * @param $filepath
 *   A string containing a relative filepath.
 *
 * @return $path
 *   A string containing the itemname/filename
 */
function internet_archive_send($config, $filepath) {
  dsm('internet_archive_send');
  //grab any existing information available for this filepath
  $ia_data = internet_archive_load_data($filepath);
  dsm($ia_data, 'did we find data in the internet archive for '.$filepath);
  if (variable_get('internet_archive_debug', FALSE)) {
    watchdog('internet_archive', 'Sending file: ' . $filepath, NULL,
	     WATCHDOG_NOTICE);
  }

  // load the S3 class
  if (! $s3 = internet_archive_new_s3()) {
    return FALSE;
  }

  $s3->setTransferId($ia_data['tid']);

  // can we read the file?
  if (! is_readable($filepath)) {
    watchdog('internet_archive', 'File is not readable: ' . $filepath .
	     ', please check that this file exists and the web user has ' .
	     'read permissions to it.', NULL, WATCHDOG_ERROR);
    return;
  }

  //grab metadata if it is available
  $metadata = array();
  $metadata = internet_archive_get_metadata($filepath);
  dsm($metadata, "back from internet_archive_get_metadata");
  //TODO: add some sort of backup in case there is no title/pattern...

  dsm(variable_get('internet_archive_itemname', NULL),
      'variable internet_archive_itemname');

  dsm(variable_get('internet_archive_bucket_title', NULL),
      'variable internet_archive_bucket_title');

  //CHECK TO SEE THE METADATA HOOK HAS SET A BUCKET NAME, THIS TAKES
  //PRECEDENT OVER THE OTHER METHODS
  if (isset($metadata['bucket-name']) && $metadata['bucket-name']) {
    $name = $metadata['bucket-name'];
    unset($metadata['bucket-name']);
    dsm($name, 'name 0');
  }
  else if ($itempattern = variable_get('internet_archive_itemname', NULL)) {
    $token_node = internet_archive_get_node_from_filepath($filepath);
    dsm($token_node, 'got my node');
    $name = token_replace($itempattern, $type = 'node', $object = $token_node,
			  $leading = '[', $trailing = ']', $options = array());

    $name = internet_archive_create_item_name($name);
    dsm($name, 'name 1');
  }
  elseif (variable_get('internet_archive_bucket_title', FALSE)) {
    $name = internet_archive_create_item_name($metadata['title']);
    dsm($name, 'name 2');
  }
  else {
    $default_item =
      variable_get('internet_archive_bucket',
		   str_replace(' ', '_',
			       variable_get('site_name', t('My Site'))));
    
    $name = internet_archive_create_item_name($default_item);
    dsm($name, 'name 3');
  }

  if (variable_get('internet_archive_queue_attempts', 0) > 0) {
    if ($ia_data['status'] == ARCHIVE_FAILED) {
      $name = $ia_data['item'];
    }
  }
  dsm($name, 'name4');

  $headers = internet_archive_process_metadata($metadata);
  dsm($headers, 'headers with metadata');

  $config['internet_archive_bucket'] = $name;
  $s3->bucket = $config['internet_archive_bucket'];

  dsm('putting bucket up');
  dsm($config, 'config');
  dsm($headers, 'headers');

  
  $status =
    $s3->putBucket($config['internet_archive_bucket'], $headers, $perms);

  if (!$status) {
    dsm("couldn't upload bucket, returning!!!!!");
    return FALSE;
  }

  // We need to set the filename based on the setting in this configuration
  // Sometimes it is a good idea to save the full $filepath as the filename
  if (! $config['internet_archive_drupal_file_path']) {
    $s3_filename = basename($filepath);
    dsm($s3_filename, 'basenaming it');
  }
  else {
    $s3_filename = $filepath;
  }
  dsm($s3_filename, 's3');

  // Put file on archive
  $mimetype = file_get_mimetype($filepath);

  //HACK for DOM, need to find a more general solution
  $pathinfo = pathinfo($filepath);
  if ($pathinfo['extension'] == 'mp2') {
    $mimetype = 'video/mpeg';
  }
  dsm($pathinfo, 'path info');
  //Log start of transfer time
  $transfer_initiated = REQUEST_TIME;
  if (is_numeric($ia_data['tid'])) {
    db_update('internet_archive')
      ->fields(array(
		     'transfer_initiated' => $transfer_initiated,
		     ))
      ->condition('tid', $ia_data['tid'])
      ->execute();
  }

  //TODO: build this into the return value of put_object so that
  //it works with remote servers as well.
  if (!$filesize = internet_archive_filesize($filepath)) {
    $filesize = 0;
  }
  dsm($filesize, 'filesize');
  dsm($config, 'config');

  //SET VARIABLES FOR THE WAIT LOOP ON BUCKET CREATTION

  //find a pause time for each loop, ideally so we get 3 nicely timed loops
  $pause = 5;

  $max = 100;
  $index = 0;
  $bucket_exists = FALSE;
  $start = strtotime('now');
  $max_run_time = 35;
    
  // There is a delay on archive.org regarding bucket creation.. so we check
  // every x seconds
  $pause = 5;
  while (!$bucket_exists && ($max_run_time + $start) > strtotime('now')){
    sleep($pause);
    if ($index > $max) {
      break;
    }
    $index++;
    if (internet_archive_bucket_exists($config['internet_archive_bucket'])) {
      $bucket_exists = TRUE;
    }

  }

  if (!$bucket_exists) {
    $msg = t("Error Code #23244 Bucket could not be found for !filepath, ".
	     "maybe bump up execution time from !max.",
	     array('!filepath' => $filepath,
		   '!max' => $max_run_time));
    
    watchdog('internet_archive', $msg, NULL, WATCHDOG_ERROR);
    drupal_set_message($msg, 'error');
    return FALSE;
  }
	 
  //TODO: better error checking if the putobject fails
  if (variable_get('internet_archive_remote', FALSE)) {
    internet_archive_remote_put_object($filepath,
				       $config['internet_archive_bucket'],
				       $s3_filename, $headers, $mimetype);
  }
  else {
    dsm('putting local file to bucket');
    if (!$s3->putObjectFile($filepath, $config['internet_archive_bucket'],
			    $s3_filename, $headers, $mimetype)) {
      dsm("error!");
      $ia_data['status'] = ARCHIVE_FAILED;
      $ia_data['attempts'] = $ia_data['attempts'] + 1;
      $ia_data['item'] = $config['internet_archive_bucket'];
      $ia_data['error'] =
	t('File transfer to Archive.org failed, transfer marked as failed.');

      watchdog('internet_archive', $ia_data['error'], NULL, WATCHDOG_ERROR);

      db_update('internet_archive')
	->fields(array(
		       'status' => $ia_data['status'],
		       'attempts' => $ia_data['attempts'],
		       'item' => $ia_data['item'],
		       ))
	->condition('in_path', $filepath)
	->execute();
      internet_archive_invoke_internet_archive($ia_data, 'failed');
      return FALSE;
    }
  }

  // Create the return filepath. We add the bucket file path if
  // the a custom domain is not being used
  if (! $config['internet_archive_drupal_file_path']) {
    $s3_filename = $config['internet_archive_bucket'] . '/' . $s3_filename;
  }

  $path = $config['internet_archive_server_url'] . $s3_filename;

  // Check to see if the host bucket is the standard AWS or
  // a bucket domain
  $pattern = '/http.?\:\/\/s3\.us\.archive\.org/';
  $hostbucket = preg_match($pattern, $path);

  // Add the file information to our custom table
  if ($filepath) {
    $node = internet_archive_get_node_from_filepath($filepath);
    $info = array(
      'item' => $config['internet_archive_bucket'],
      'in_path' => $filepath,
      'filename' => basename($filepath),
      'filesize' => $filesize,
      'status' => ARCHIVE_TRANSFERRED,
      'attempts' => 1,
      'transfer_initiated' => $transfer_initiated,
      'md5' => md5_file($filepath),
      'date' => REQUEST_TIME,
      'archive_url' => 'http://www.archive.org/download/' .
      $config['internet_archive_bucket'] . '/' . basename($filepath),
      'nid' => $node->nid,
    );

    //check if entry already exists from queue
    $s3_data = internet_archive_load_data($filepath);
    if ($s3_data['tid']) {
      if ($s3_data['attempts'] != 0) {
        $info['attempts'] = $s3_data['attempts'] + 1;
      }

      db_update('internet_archive')
  ->fields(array(
        'item' => $info['item'],
        'in_path' => $info['in_path'],
        'filename' => $info['filename'],
        'filesize' => $info['filesize'],
        'status' => $info['status'],
        'attempts' => $info['attempts'],
        'transfer_initiated' => $info['transfer_initiated'],
        'md5' => $info['md5'],
        'date' => $info['date'],
        'archive_url' => $info['archive_url'],
        'nid' => $info['nid'],
      ))
  ->condition('tid', $s3_data['tid'])
  ->execute();
    }
    else {
      $sql =
	"INSERT into {internet_archive} ".
	"(item, in_path, filename, filesize, status, attempts, ".
	" transfer_initiated, md5, date, archive_url, nid) " .
	"VALUES (:item, :in_path, :filename, :filesize, :status, " .
	"        :attempts, :transfer_initiated, :md5, :date, :archive_url, " .
	"        :nid)";

      $args = array(':item' => $info['item'],
		    ':in_path' => $info['in_path'],
		    ':filename' => $info['filename'],
		    ':filesize' => $info['filesize'],
		    ':status' => $info['status'],
		    ':attempts' => $info['attempts'],
		    ':transfer_initiated' => $info['transfer_initiated'],
		    ':md5' => $info['md5'],
		    ':date' => $info['date'],
		    ':archive_url' => $info['archive_url'],
		    ':nid' => $info['nid']);
      dsm($args, 'args');
      db_query($sql, $args);
    }

    $final_data = internet_archive_load_data($info['in_path']);
    dsm($final_data, 'final data');
    internet_archive_invoke_internet_archive($final_data, 'transferred');
    dsm('done with invoking internet_archive_invoke_internet_archive');
  }
  else {
    $log_entry = array(
      'tid' => $ia_data['tid'],
      'message' => t('No filepath available after upload attempt!'),
      'message_data' => $ia_data,
      'type' => ARCHIVE_LOG_ERROR,
    );
    internet_archive_log($log_entry);
    return FALSE;
  }

  return $path;
}

/**
 * Grabs all internet archive transfer information based on node id.
 *
 * @param $nid
 *   Node id
 *
 * @return
 *   An array of internet archive files associated with the node.
 */
function internet_archive_node_files($nid) {
  dsm('internet_archive_node_files');
  $result = db_query("SELECT * FROM {internet_archive} WHERE nid = :nid",
		     array(':nid' => $nid));
  $files = array();
  while ($archive_data = $result->fetchAssoc()) {
    $files[] = $archive_data;
  }

  return $files;
}

/**
 * Updates an item's metadata at archive.org based on the source filepath.
 *
 * @param $filepath
 *   A source filepath of a file transferred to archive.org
 */
function internet_archive_update_item($filepath) {
  dsm('internet_archive_update_item');
  $archive_data = internet_archive_load_data($filepath);

  //grab all the necessary information
  $config = internet_archive_default_config();

  if (variable_get('internet_archive_debug', FALSE)) {
    watchdog('internet_archive', 'Updating item: ' .
	     $archive_data['item'], NULL, WATCHDOG_NOTICE);
  }

  // load the S3 class
  if (! $s3 = internet_archive_new_s3()) {
    return FALSE;
  }
  $s3->setTransferId($archive_data['tid']);

  dsm($archive_data, 'archive data for node');
  //grab metadata if it is available
  $metadata = array();
  $metadata = internet_archive_get_metadata($filepath);

  $headers = internet_archive_process_metadata($metadata);

  //this tells archive.org to destroy original metadata
  $headers['x-amz-ignore-preexisting-bucket'] = 1;

  $config['internet_archive_bucket'] = $archive_data['item'];
  $s3->bucket = $config['internet_archive_bucket'];

  dsm('about to putBucket with updated metadata');
  // Send new metadata
  $s3->putBucket($config['internet_archive_bucket'], $headers, $perms);

  $log_entry = array(
    'tid' => $archive_data['tid'],
    'message' => t('Updated metadata at archive.org'),
    'message_data' => $archive_data,
    's3_data' => $headers,
    'type' => ARCHIVE_LOG_NOTICE,
  );

  internet_archive_log($log_entry);
}

/**
 * Deletes all files in an item at archive.org
 *
 * @param $archive_data
 * An array of archive.org information from one of the 
 * internet_archive_load_data functions.
 */
function internet_archive_delete_item($archive_data) {

  //grab all the necessary information
  $config = internet_archive_default_config();

  // load the S3 class
  if (! $s3 = internet_archive_new_s3()) {
    return FALSE;
  }
  $s3->setTransferId($archive_data['tid']);

  $config['internet_archive_bucket'] = $archive_data['item'];
  $s3->bucket = $config['internet_archive_bucket'];

  $s3->deleteObject($config['internet_archive_bucket'],
		    $archive_data['filename']);
}


/**
 * Deletes all files in an item at archive.org
 *
 * @param $archive_data
 * An array of archive.org information from one of the 
 * internet_archive_load_data functions.
 */
function internet_archive_delete_files($archive_data) {

  //grab all the necessary information
  $config = internet_archive_default_config();

  // load the S3 class
  if (! $s3 = internet_archive_new_s3()) {
    return FALSE;
  }
  $s3->setTransferId($archive_data['tid']);

  $config['internet_archive_bucket'] = $archive_data['item'];
  $s3->bucket = $config['internet_archive_bucket'];

  $s3->deleteFiles($config['internet_archive_bucket'],
		   $archive_data['filename']);
}

/**
 * Harvests failed files and adds them back to the transfer queue
 * based on number of allowed attemps in administrative settings
 */
function internet_archive_harvest_failed() {
  dsm('internet_archive_harvest_failed');
  $attempts = variable_get('internet_archive_queue_attempts', 0) + 1;
  $result =
    db_query("SELECT in_path FROM {internet_archive} " .
	     "WHERE status = :status AND attempts < :attempts",
	     array(':status' => ARCHIVE_FAILED, ':attempts' => $attempts));

  $filepaths = array();
  while ($filepath = $result->fetchField()) {
    $filepaths[] = $filepath;
  }

  return $filepaths;
}

/**
 * Optional administrative setting looks for items in the
 * internet_archive table that are set as queued, never started transferring
 * and no longer exist in the current drupal queue. For sites with very large
 * files this may be necessary in cases that the drupal queue expires before
 * the items are sent.
 *
 * @return $candidates
 *   An array of filepaths to be queued
 */
function internet_archive_harvest_expired_queued() {
  dsm('internet_archive_harvest_expired_queued');
  //grab all the queued non-transferred items from internet_archive table
  $ia_result =
    db_query("SELECT * FROM {internet_archive} " .
	     "WHERE status = :status " .
	     "AND transfer_initiated = :transfer_initiated",
	     array(':status' => 'queued', ':transfer_initiated' => 0));
  while ($ia_data = $ia_result->fetchAssoc()) {
    $ia_queued[] = $ia_data['in_path'];
  }

  if (isset($ia_queued) && $ia_queued) {
    //grab all the currently queued transfer items from drupal queue
    $queue_result = db_query("SELECT * FROM {queue} WHERE name = :name",
			     array(':name' => 'internet_archive_send_file'));
    while ($queue_data = $queue_result->fetchAssoc()) {
      $queue_queued[] = unserialize($queue_data['data']);
    }
    if ($queue_queued) {
      $candidates = array_diff($ia_queued, $queue_queued);
    }
    else {
      $candidates = $ia_queued;
    }
  }

  //take candidates and re-add them to the queue if there is room
  if (isset($candidates) && $candidates) {
    $transfer_queue = DrupalQueue::get('internet_archive_send_file');

    $filepaths = $candidates;
    foreach ($filepaths as $key => $filepath) {
      if (file_exists($filepath)) {
	$node = internet_archive_get_node_from_filepath($filepath);
	$ia_info = internet_archive_load_data($filepath);
	$message =
	  t('Added transfer back to queue due to stale queue status.');
	
	$log_data = array(
			  'tid' => $ia_info['tid'],
			  'message' => $message,
			  'message_data' => $ia_info,
			  'type' => ARCHIVE_LOG_NOTICE,
			  );
	
	//add the file to queue
	$transfer_queue->createItem($filepath);
	internet_archive_log($log_data);
      }
    }
  }
  else {
    return FALSE;
  }
}

/**
 * Validates transfers to archive.org by checking the contents of the item
 * via S3
 */
function internet_archive_validate_transfers($nid = null) {
  dsm('internet_archive_validate_transfers');
  //how many times should we attempt to transfer failed files
  $attempts = variable_get('internet_archive_queue_attempts', 0) + 1;
  dsm($attempts, 'attempts');

  if ($nid) {
    //only grab 10 at a time to avoid pounding archive.org
    $result = db_query("SELECT * FROM {internet_archive} ".  
		       "WHERE nid = :nid ".
		       "AND (status = :transferred OR ".
		       "(status = :failed AND attempts <= :attempts)) ".
		       "LIMIT 10",
		       array(':nid' => $nid,
			     ':transferred' => ARCHIVE_TRANSFERRED,
			     ':failed' => ARCHIVE_FAILED,
			     ':attempts' => $attempts));
  }
  else {
    //only grab 10 at a time to avoid pounding archive.org
    $result = db_query("SELECT * FROM {internet_archive} ".  
		       "WHERE (status = :transferred OR ".
		       "(status = :failed AND attempts <= :attempts)) ".
		       "LIMIT 10",
		       array(':transferred' => ARCHIVE_TRANSFERRED,
			     ':failed' => ARCHIVE_FAILED,
			     ':attempts' => $attempts));
  }
  while ($archive_info = $result->fetchAssoc()) {
    dsm($archive_info, 'ai');
    $valid = internet_archive_validate_transfer($archive_info['tid']);
    dsm($valid, 'valid');
    if (!$valid && (REQUEST_TIME - $archive_info['date']) > (8*60*60)) {
      db_update('internet_archive')
	->fields(array(
		       'status' => ARCHIVE_FAILED,
		       ))
	->condition('tid', $archive_info['tid'])
	->execute();
      $archive_info['status'] = ARCHIVE_FAILED;
      $archive_info['error'] = 
	t('Validation failed, source file does not exist at Archive.org ' .
	 'after 8 hours. Marked as failed.');

      internet_archive_invoke_internet_archive($archive_info, 'failed');
    }
    elseif ($valid) {
      db_update('internet_archive')
	->fields(array(
		       'status' => ARCHIVE_VALIDATED,
		       ))
	->condition('tid', $archive_info['tid'])
	->execute();
      $archive_info['status'] = ARCHIVE_VALIDATED;
      internet_archive_invoke_internet_archive($archive_info, 'validated');
    }
  }
}

/**
 * Validates a single transfer by checking if the item contents are empty
 * at archive.org via S3
 *
 * @param $tid
 * An internet_archive transfer ID
 *
 * @return
 * TRUE or FALSE
 */
function internet_archive_validate_transfer($tid) {
  dsm('internet_archive_validate_transfer');
  $data = internet_archive_load_data_tid($tid);

  if (!$data) {
    return FALSE;
  }

  $derivatives = internet_archive_get_derivatives($data['item']);
  dsm($derivatives, 'derivs');
  if (!$derivatives) {
    return FALSE;
  }
  else {
    return TRUE;
  }
}

/**
 * Creates a URL to a derivative file WITHOUT checking to
 * see if the file actually exists on archive.org
 *
 * Use internet_archive_derivative if you need a more accurate, but
 * much slower solution.
 *
 * @param $nid
 *   A node ID containing archive.org enabled field data
 * @param @ext
 *   The extension of the derivative you want ex. ogv
 *
 * @return full, assumed url to the derivative or FALSE if no transferred
 * files are found on the node
 */
function internet_archive_simple_derivative($nid, $ext) {
  $archive = db_query("SELECT * FROM {internet_archive} WHERE nid = :nid",
		      array(':nid' => $nid))->fetchAssoc();
  if ($archive['status'] == ARCHIVE_TRANSFERRED) {
    $pathinfo = pathinfo($archive['filename']);
    return 'http://www.archive.org/download/' . $archive['item'] . '/' .
      $pathinfo['filename'] . '.' . $ext;
  }
  else {
    return FALSE;
  }
}

/**
 * Creates a URL to a derivative file by running an S3 call to archive.org
 *
 * Use internet_archive_simple_derivative if you would like a faster, but less
 * accurate solution
 *
 * @param $item_name
 *   An archive.org item/bucket name
 * @param @extension
 *   The extension of the derivative you want ex. ogv
 *
 * @return an array of all derivative paths found matching the extension
 */
function internet_archive_derivative($item_name, $extension) {
  $s3 = internet_archive_new_s3();
  $archive_info = internet_archive_load_data_item($item_name);
  $s3->setTransferId($archive_info['tid']);

  $bucket_info = $s3->getBucket($item_name);

  $derivative_paths = array();

  if ($bucket_info) {
    foreach ($bucket_info as $filename => $fileinfo) {
      $pathinfo = pathinfo($filename);
      if ($pathinfo['extension'] == $extension) {
        $derivative_paths[$filename] = 'http://www.archive.org/download/' .
	  $item_name . '/' . $filename;
      }
    }
  }

  return $derivative_paths;
}

/**
 * Attempts to check whether or not an item/bucket has been
 * created at archive.org. Basically calls up the page and does a
 * header check.
 *
 * @param $item_name
 *   A string identifier for the item at archive.org
 *
 * @return
 *   TRUE or FALSE
 */
function internet_archive_bucket_exists($item_name) {
  dsm('internet_archive_bucket_exists');
  $bucket_url = 'https://www.archive.org/details/' . $item_name;
  dsm($bucket_url, 'looking for bucket with url');
  if (internet_archive_validate_url($bucket_url)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Gets a list of all items/buckets created via S3
 *
 * @return
 *   An object containing all the bucket/item information
 */
function internet_archive_buckets() {
  $s3 = internet_archive_new_s3();
  $s3->setTransferId(0);

  $buckets = $s3->listBuckets(TRUE);

  return $buckets;
}

/**
 * Gets derivatives for a specific item at archive.org
 *
 * @param $item_name
 *   A string containing the item identifier at archive.org
 * @param $extension
 *   Optional file extension like .mpeg to limit derivative results
 *
 * @return
 *   An object containing all of the derivatives for an item.
 */
function internet_archive_get_derivatives($item_name, $extension = NULL) {
  dsm('internet_archive_get_derivatives');
  $s3 = internet_archive_new_s3();
  $archive_info = internet_archive_load_data_item($item_name);
  $s3->setTransferId($archive_info['tid']);

  //NEED TO ADD HERE..
  $bucket_info = $s3->getBucket($item_name);
  dsm($bucket_info, 'bucket info');
  if ($bucket_info) {
    if ($extension) {
      dsm($extension, 'extension');
      foreach ($bucket_info as $filename => $fileinfo) {
        $pathinfo = pathinfo($filename);
        if ($pathinfo['extension'] == $extension) {
          return $fileinfo;
        }
      }
      return FALSE;
    }
    else {
      return $bucket_info;
    }
  }
  else {
    return FALSE;
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_is_archive_format($filename) {
  //formats derived by archive.org
  //TODO: add more formats for audio, etc.
  $archive_formats = array('mpeg', 'ogv', 'mp4');
  $pathinfo = pathinfo($filename);
  if (in_array($pathinfo['extension'], $archive_formats)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Checks for new derivative information from uploaded files and stores that 
 * information as serialized data in the internet_archive table. Stops 
 * checking for metadata when a file has completed deriving.
 *
 * @param $limit
 *   An integer which limits how many files to check in a single run at 
 *   archive.org
 */
function internet_archive_store_derivatives($nid, $limit = 25) {
  dsm('internet_archive_store_derivatives');

  if ($nid) {
    // only grab items that have already been successfully uploaded
    $sql =
      "SELECT * FROM {internet_archive} " .
      "WHERE status = :status " .
      "AND nid = :nid ".
      "AND (derivatives IS NULL OR derivatives <> :derivatives) " .
      "ORDER BY date ASC ";
      $args = array(
		    ':nid' => $nid,
		    ':status' => ARCHIVE_VALIDATED,
		    ':derivatives' => 'failed',
		    );
  }
  else {
    // only grab items that have already been successfully uploaded
    $sql =
      "SELECT * FROM {internet_archive} " .
      "WHERE status = :status " .
      "AND (derivatives IS NULL OR derivatives <> :derivatives) " .
      "ORDER BY date ASC ";
    $args = array(':status' => ARCHIVE_VALIDATED,
		  ':derivatives' => 'failed',
		  );
  }

  $results = db_query_range($sql, 0, $limit, $args);
  
  while ($item = $results->fetchAssoc()) {
    //+1 to account for the original file
    $expected_derivatives =
      variable_get('internet_archive_derivatives', 3) + 1;

    //if we are uploading a file in a format archive.org derives it will not
    //re-derive it therefore we need to decrement the expected derivatives by 1
    if (internet_archive_is_archive_format($item['filename'])) {
      $expected_derivatives = $expected_derivatives - 1;
    }

    unset($derivatives);
    $derivatives = internet_archive_get_derivatives($item['item']);
    dsm($derivatives, 'found derivatives');
    if ($derivatives && (count($derivatives) >= $expected_derivatives)) {
      db_update('internet_archive')
	->fields(array(
		       'status' => ARCHIVE_DERIVED,
		       ))
	->condition('item', $item['item'])
	->execute();
      
      $item['derivatives'] = serialize($derivatives);
      internet_archive_invoke_internet_archive($item, 'derived');
    }
    elseif ((REQUEST_TIME - $item['date']) > 172800) {
      // if derivatives are not completed after 2 days, check to see if
      //transfer validates
      $valid = internet_archive_validate_transfer($item['tid']);
      if (!$valid) {
        // if it doesn't validate, mark as failed for reprocessing
        db_update('internet_archive')
	  ->fields(array(
			 'status' => ARCHIVE_FAILED,
			 ))
	  ->condition('tid', $item['tid'])
	  ->execute();
        internet_archive_invoke_internet_archive($item, 'failed');
      }
      else {
        // if it does validate, mark derivatives as failed
        db_update('internet_archive')
	  ->fields(array(
			 'derivatives' => 'failed',
			 ))
	  ->condition('item', $item['item'])
	  ->execute();
        internet_archive_invoke_internet_archive($item, 'derivativefailed');
      }
    }

    if ($derivatives && (count($derivatives) > 0)) {
      db_update('internet_archive')
	->fields(array(
		       'derivatives' => serialize($derivatives),
		       ))
	->condition('item', $item['item'])
	->execute();
    }
  }
  return;
}


/**
 * Arthur Foelsche, from the module: http://www.drupal.org/project/media_mover
 *
 * This function takes apart the form keys that are used to
 * keep module data seperate and hand back an array of parsed
 * values back to a requestor
 *
 * @param $element
 * @return array
 */
function internet_archive_validate_form_data_extract($element) {
  // extract each value from the form element to
  // be passed back in an array
  foreach (element_children($element) as $key) {
    // Build the pattern to replace with
    $pattern = "/^step(.*)--/";
    $value_name = preg_replace($pattern, '', $key);
    $values[$value_name] = $element[$key]['#post'][$key];
  }
  return $values;
}

/**
 * Confirmation for manual internet archive transfer
 *
 * @see internet_archive_transfer_confirm_submit()
 *
 * @ingroup forms
 */
function internet_archive_transfer_confirm($form, $drupal_form, $filepath) {
  $filepath = str_replace('!-!', '/', urldecode($filepath));
  watchdog('internet_archive',
	   'Executing internet_archive_transfer_confirm() with filepath: ' .
	   $filepath);

  $output .= '<br />' .
    t('You are about to transfer: %file_name to Archive.org',
      array('%file_name' => $filepath));
  
  $output .= '<br /><strong>' .
    t('Depending on the size of the file, this could take awhile.') .
    '</strong><br /><br />';

  $form['markup'] = array(
    '#type' => 'markup',
    '#value' => $output,
  );
  $form['filepath'] = array(
    '#type' => 'value',
    '#value' => $filepath,
  );
  $form['original_referrer'] = array(
    '#type' => 'value',
    '#value' => $_SERVER['HTTP_REFERER'],
  );

  return confirm_form($form, t('Are you sure you want to transfer this file?'),
		      NULL, $description = '', t('Transfer'), t('Cancel'));
}

/**
 * Takes file data from internet archive utility link and starts
 * a manual file transfer to archive.org
 * TODO: find a better solution for clearing the file cache.
 *
 * @ingroup forms
 */
function internet_archive_transfer_confirm_submit($form_id, &$form_state) {
  dsm('internet_archive_transfer_confirm_submit');
  dsm($form_state, 'fs');
  
  $status = internet_archive_default_send($form_state['values']['filepath']);

  if ($status) {
    drupal_set_message('File transferred successfully, please note there ' .
		       'may be a short delay before the file is available ' .
		       'on Archive.org');
  }
  else {
    drupal_set_message('Error Code #5857 The file: ' .
		       $form_state['values']['filepath'] . ' was not sent.',
		       'error');
  }

  //clear the page cache so updated file information appears on node
  //TODO: there has to be a less drastic way to accomplish the goal
  dsm('did not flush cache');
  //drupal_flush_all_caches();
}

/**
 * Sends a file to archive.org using mostly default settings
 * TODO: remove extra watchdog debug
 *
 * @see internet_archive_default_config()
 *
 * @param $filepath
 *   A string containing a file path.
 *
 * @return
 */
function internet_archive_default_send($filepath) {
  dsm('internet_archive_default_send');
  //grab all the necessary information
  $config = internet_archive_default_config();

  //send the file
  $status = internet_archive_send($config, $filepath);

  return $status;
}

/**
 * Builds a default archive.org transfer configuration using information
 * provided on the general settings page.
 *
 * @return $config
 *   An array containing basic s3 configuration info.
 */
function internet_archive_default_config() {
  $config = array();
  $config['internet_archive_bucket'] =
    variable_get('internet_archive_bucket',
		 str_replace(' ', '_', variable_get('site_name',
						    t('My Site'))));
  $config['internet_archive_drupal_file_path'] = 0;
  $config['advanced'] = array(
    'internet_archive_server_url' =>
    variable_get('internet_archive_default_server_url',
		 "https://s3.us.archive.org/"),
  );

  return $config;
}

/**
 * Invoke a hook_internet_archive() operation in all modules.
 *
 * @param &$node
 *   An internet_archive data object.
 * @param $op
 *   A string containing the name of the internet_archive operation.
 * @return
 *   The returned value of the invoked hooks.
 */
function internet_archive_invoke_internet_archive(&$archive_data, $op) {
  dsm('internet_archive_invoke_internet_archive');
  dsm($archive_data, 'archive data for ' .$op);
  $return = array();
  foreach (module_implements('internet_archive') as $name) {
    $function = $name . '_internet_archive';
    $result = $function($archive_data, $op);
    if (isset($result) && is_array($result)) {
      $return = array_merge($return, $result);
    }
    elseif (isset($result)) {
      $return[] = $result;
    }
  }
  return $return;
}

/**
 * Implements hook_internet_archive().
 */
function internet_archive_internet_archive(&$archive_data, $op) {
  dsm('internet_archive_internet_archive');
  switch ($op) {
    case 'harvested':
      break;

    case 'queued':
      if ($archive_data['status'] != ARCHIVE_FAILED) {
        $message = t('Queued for transfer');
      }
      else {
        $message = t('Requeued for transfer due to previous failure, attempt '.
		     '%attempt of %retries',
		     array('%attempt' => $archive_data['attempts'] + 1,
			   '%retries' =>
			   variable_get('internet_archive_queue_attempts', 0)
			   + 1));
      }
      $log_data = array(
        'tid' => $archive_data['tid'],
        'message' => $message,
        'message_data' => $archive_data,
        'type' => ARCHIVE_LOG_NOTICE,
      );
      internet_archive_log($log_data);
      break;

    case 'transferring':
      $log_data = array(
        'tid' => $archive_data['tid'],
        'message' => t('Transfer started to Archive.org'),
        'message_data' => $archive_data,
        'type' => ARCHIVE_LOG_NOTICE,
      );
      internet_archive_log($log_data);
      break;

    case 'transferred':
      $log_data = array(
        'tid' => $archive_data['tid'],
        'message' => t('Transfer completed to Archive.org'),
        'message_data' => $archive_data,
        'type' => ARCHIVE_LOG_NOTICE,
      );
      internet_archive_log($log_data);
      break;

    case 'validated':
      $log_data = array(
        'tid' => $archive_data['tid'],
        'message' => t('Validated, source file exists at Archive.org'),
        'message_data' => $archive_data,
        'type' => ARCHIVE_LOG_NOTICE,
      );
      internet_archive_log($log_data);
      break;

    case 'derived':
      $log_data = array(
        'tid' => $archive_data['tid'],
        'message' => t('Derivative processing at Archive.org completed'),
        'message_data' => $archive_data,
        'type' => ARCHIVE_LOG_NOTICE,
      );
      internet_archive_log($log_data);
      break;

    case 'failed':
      $log_data = array(
        'tid' => $archive_data['tid'],
        'message' => $archive_data['error'],
        'message_data' => $archive_data,
        'type' => ARCHIVE_LOG_ERROR,
      );
      internet_archive_log($log_data);
      break;
  }
}

/**
 * Produces the statistical report at admin/reports/internet_archive/stats with
 * some aggregate upload and download information
 */
function internet_archive_reports_statistics() {
  $header = array('Stat', 'Value');
  $count = db_query("SELECT COUNT(*) FROM {internet_archive}")->fetchField();

  if (module_exists('internet_archive_download')) {
    $file_rows[] =
      array('Downloaded',
	    db_query("SELECT COUNT(*) FROM {internet_archive_download} " .
		     "WHERE status = :status",
		     array(':status' => 'downloaded'))->fetchField());
  }
  $file_rows[] =
    array('Derived',
	  db_query("SELECT COUNT(*) FROM {internet_archive} " .
		   "WHERE status = :status",
		   array(':status' => 'derived'))->fetchField());

  $file_rows[] =
    array('Validated',
	  db_query("SELECT COUNT(*) FROM {internet_archive} " .
		   "WHERE status = :status",
		   array(':status' => 'validated'))->fetchField());
  
  $file_rows[] =
    array('Transferred',
	  db_query("SELECT COUNT(*) FROM {internet_archive} " .
		   "WHERE status = :status",
		   array(':status' => 'transferred'))->fetchField());
  
  $file_rows[] =
    array('Transferring',
	  db_query("SELECT COUNT(*) FROM {internet_archive} ".
		   "WHERE status = :status",
		   array(':status' => 'transferring'))->fetchField());

  $file_rows[] =
    array('Queued',
	  db_query("SELECT COUNT(*) FROM {internet_archive} ".
		   "WHERE status = :status",
		   array(':status' => 'queued'))->fetchField());
  
  $file_rows[] =
    array('Failed',
	  db_query("SELECT COUNT(*) FROM {internet_archive} " .
		   "WHERE status = :status",
		   array(':status' => 'failed'))->fetchField());
  
  $file_table = theme('table',array('header'=> $header, 'rows' => $file_rows));

  $total = db_query("SELECT sum(filesize) FROM {internet_archive} ".
		    "WHERE status = :status OR status = :status",
		    array(':status' => 'validated',
			  ':status' => 'derived'))->fetchField();
  $transfer_rows[] = array('Total Data Uploaded',
			   round($total / 1024 / 1024) . ' MB');
  
  $transfer_rows[] = array('Upload Rate Average (overall)',
			   internet_archive_transfer_rate($limit = 0) .
			   ' Mb/sec | ' .
			   internet_archive_transfer_rate($limit = 0, 'time').
			   ' min/file');
  if ($count > 20) {
    $transfer_rows[] = array('Upload Rate Average (last 15 transfers)',
			     internet_archive_transfer_rate(15) .
			     ' Mb/sec | ' .
			     internet_archive_transfer_rate($limit = 15,
							    'time') .
			     ' min/file');
  }
  if ($count > 55) {
    $transfer_rows[] = array('Upload Rate Average (last 50 transfers)',
			     internet_archive_transfer_rate(50) . ' Mb/sec | '.
			     internet_archive_transfer_rate($limit = 50,
							    'time') .
			     ' min/file');
  }

  $val_plus_derived = db_query("SELECT avg(filesize) " .
			       "FROM {internet_archive} " .
			       "WHERE status = :status OR status = :status",
			       array(':status' => 'validated',
				     ':status' => 'derived'))->fetchField();
  
  $transfer_rows[] = array('Average Filesize',
			   round($val_plus_derived / 1024 / 1024, 4) . ' MB');

  $transfer_table = theme('table', array('header' => $header,
					 'rows' => $transfer_rows));

  if (module_exists('internet_archive_download')) {
    $download_stats = internet_archive_download_statistics();
    $download_table = internet_archive_download_table($download_stats);
  }

  $output = '<h3>Internet Archive Statistics</h3><br />';
  $output .= '<div class="admin-panel">';
  $output .= '<h4 style="border-bottom:1px solid black">File Status</h4>';
  $output .= $file_table;
  $output .= '</div>';
  $output .= '<div class="admin-panel">';
  $output .= '<h4 style="border-bottom:1px solid black">Upload Stats</h4>';
  $output .= $transfer_table;
  $output .= '</div>';
  if ($download_table) {
    $output .= '<div class="admin-panel">';
    $output .= '<h4 style="border-bottom:1px solid black">Download Stats</h4>';
    $output .= $download_table;
    $output .= '</div>';
  }

  return $output;
}

/**
 * Produces the upload report at admin/reports/internet_archive showing a summary
 * of recent file uploads
 */
function internet_archive_reports_log() {
  $output .= 'Typical file status process is: Queued -> Transferring -> '.
    'Transferred -> Validated- > Derived';
  
  $output .= '<br />For information on Archive.org status, please ' .
    '<a href="http://blog.archive.org/">checkout their blog</a> and/or ' .
    'subscribe to <a href="http://twitter.com/internetarchive">their '.
    'twitter feed</a>.<br /><br />';
  $output .= internet_archive_uploads();
  return $output;
}

/**
 * Produces the system messages report at admin/reports/internet_archive/log showing
 * a listing of all system log messages sorted by date.
 */
function internet_archive_reports_system_messages() {
  if (arg(4) == 'all') {
    $output .=
      t('All status messages recorded by the system are shown below.') .
      l(' Click here to view only warnings and errors.',
	'admin/reports/internet_archive/log');
  }
  else {
    $output .=
      t('All warning and error level status messages recorded by the system '.
	'are shown below.') .
      l(' Click here to view all messages, including notices.',
	'admin/reports/internet_archive/log/all');
  }
  $output .= internet_archive_log_view('global');
  return $output;
}

/**
 * Builds the table view of recent uploads for the upload report.
 *
 * @param $limit
 *   Number of upload entries to show on a single page.
 */
function internet_archive_uploads() {
  $page_number = arg(3);
  $results_per_page = variable_get('internet_archive_results_per_page', 100);

  if ($page_number && $page_number > 1) {
    $min = (($results_per_page) * $page_number) - $results_per_page;
  }
  else {
    $page_number = 1;
    $min = 0;
  }
  
  $result =db_query_range("SELECT * FROM {internet_archive} ".
			  "ORDER BY transfer_initiated DESC",
			  $min, $results_per_page);
  
  $header = array('ID', 'Node', 'Filename', 'Filesize (MB)', 'Start', 'Finish',
		  'Time(min)<br />Rate(Mb/sec)', 'Status', 'Log');
  
  $rows = array();

  $has_results = FALSE;
  $count = 0;
  while ($archive_data = $result->fetchAssoc()) {
    $count ++;
    $has_results = TRUE;
    unset($transfer_time);
    unset($filesize);
    unset($transfer_rate);
    unset($filename);

    if ($archive_data['date'] > 0 && $archive_data['transfer_initiated'] > 0) {
      $transfer_time =
	($archive_data['date'] - $archive_data['transfer_initiated']) / 60;
      $transfer_time =round($transfer_time, 2);
    }
    else {
      $transfer_time = 'N/A';
    }

    if ($archive_data['filesize'] > 0) {
      $filesize = round(($archive_data['filesize'] / 1024 / 1024), 2);
    }
    else {
      $filesize = 'N/A';
    }

    if ($archive_data['filesize'] > 0 && $archive_data['date'] > 0 &&
	$archive_data['transfer_initiated'] > 0) {

      $transfer_rate = $archive_data['filesize'] * 8 / 1000 / 1000;

      $transfer_rate = $transfer_rate /
	($archive_data['date'] - $archive_data['transfer_initiated']);
      
      $transfer_rate = round($transfer_rate, 4);
    }
    else {
      $transfer_rate = 'N/A';
    }

    if (strlen($archive_data['filename']) > 40) {
      $filename = substr($archive_data['filename'], 0, 40) . '...';
    }
    else {
      $filename = $archive_data['filename'];
    }

    $rows[] =
      array(l($archive_data['tid'], 'http://www.archive.org/details/' .
	      $archive_data['item']),
	    l($archive_data['nid'], 'node/' . $archive_data['nid']),
	    $filename, $filesize, $archive_data['transfer_initiated'],
	    $archive_data['date'],
	    $transfer_time . '<br />' . $transfer_rate,
	    $archive_data['status'],
	    l('View', 'ia/log/' . $archive_data['tid']));
  }

  if ($has_results) {
    $rows = internet_archive_format_dates($rows, $limit);
    $table = theme('table', array('header' => $header, 'rows' => $rows));
  }
  else {
    $table = "<h3>" . t("There are no more results to show.") . "</h3>";
  }

  if ($page_number > 1) {
    $prev_page = $page_number - 1;
    $table .= "<br/>" .
      l("<<<<< Previous ", "admin/reports/internet_archive/" . $prev_page);
    $table .= "&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
  }

  if ($has_results && $count == $results_per_page) {
    $next_page = $page_number + 1;
    $table .= l(" Next >>>>>>", "admin/reports/internet_archive/".$next_page);
  }
  return $table;
}

/**
 * Formats dates for display on the report pages.
 *
 * @param $rows
 *   An array of report rows with data data
 * @param $limit
 *   The number of rows that will be displayed on a single page
 *
 * @return
 *   An array of report rows with adjusted friendly date data
 */
function internet_archive_format_dates($rows) {
  $counter = 0;
  $formatted_rows = array();

  foreach ($rows as $key => $row) {
    $formatted_rows[$key] = $row;
    if (!$formatted_rows[$key][4]) {
      $formatted_rows[$key][4] = 'N/A';
    }
    else {
      $formatted_rows[$key][4] = date("m/d/y g:ia", $row[4]);
    }
    if (!$formatted_rows[$key][5]) {
      $formatted_rows[$key][5] = 'N/A';
    }
    else {
      $formatted_rows[$key][5] = date("m/d/y g:ia", $row[5]);
    }
    $counter++;
  }

  return $formatted_rows;
}

/**
 * Calculates the overall transfer rate for recent transfers
 *
 * @param $limit
 *   The number of transfers to use in the calculation, starts at most recent
 *   and goes backwards
 * @param $format
 *   The method of calculation, either rate or time.
 *
 * @return
 *   A rounded decimal containing either the rate in mbits/sec or total time in minutes.
 */
function internet_archive_transfer_rate($limit = 0, $format = 'rate') {
  $total_seconds = 0;
  $total_bytes = 0;
  $counter = 0;

  $result =
    db_query("SELECT * FROM {internet_archive} ".
	     "WHERE status = :status OR status = :status ".
	     "ORDER BY tid DESC",
	     array(':status' => 'validated', ':status' => 'derived'));
  
  while ($archive_data = $result->fetchAssoc() ) {
    if ($archive_data['transfer_initiated'] != 0 &&
	$archive_data['date'] != 0 && $archive_data['filesize'] != 0) {

      $total_bytes = $total_bytes + $archive_data['filesize'];
      $total_seconds = $total_seconds + ($archive_data['date'] -
					 $archive_data['transfer_initiated']);
      $counter++;
    }

    if ($limit != 0 && $counter >= $limit) {
      break;
    }
  }

  switch ($format) {
    case 'rate':
      if ($total_bytes && $total_seconds > 0) {
        $bits = $total_bytes * 8;
        $mbits = $bits / 1000 / 1000;
        $mbits_sec = $mbits / $total_seconds;
        return round($mbits_sec, 4);
      }
      else {
        return 'N/A';
      }
      break;

    case 'time':
      if ($total_seconds > 0) {
        $minutes = $total_seconds / $counter / 60;
        return round($minutes, 2);
      }
      else {
        return 'N/A';
      }
      break;
  }
}

/********************************************************
 * Drupal Queue Integration
 ********************************************************
 */

/**
 * Themes the archive.org queue status display based on the queue example
 * provided by rfay in the D7 examples module.
 *
 * @param $variables
 *  An array containing queue items.
 *
 * @return $output
 *   Themed table output if available, empty status if not.
 */
function theme_queue_items() {
  dsm('theme_queue_items');
  // TODO Number of parameters in this theme funcion does not match number of parameters found in hook_theme.
  $items = $variables['items'];
  $rows = array();
  foreach ($items as &$item) {
    //grab file information
    $filepath = unserialize($item['data']);
    $filesize = internet_archive_filesize($filepath);
    $node = internet_archive_get_node_from_filepath($filepath);

    array_unshift($item, $filepath, $filesize, l($node->nid, 'node/' . $node->nid));

    if ($item['expire'] > 0) {
      $item['expire'] = t("Claimed: expires %expire", array('%expire' => date('r', $item['expire'])));
    }
    else {
      $item['expire'] = t('Unclaimed');
    }
    $item['created'] = date('r', $item['created']);
    unset($item['data']);
    $rows[] = $item;
  }
  if (!empty($rows)) {
    $header = array(t('Filename'), t('Filesize'), t('Node'), t('Queue Item ID'), t('Claimed/Expiration'), t('Created'));
    $output = theme('table', array('header' => $header, 'rows' => $rows));
    return $output;
  }
  else {
    return t('There are no items currently in the queue.');
  }
}

/**
 * This is a drush function
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_transfer_queue() {
  require_once DRUPAL_ROOT . '/' .
    drupal_get_path('module', 'internet_archive') .
    '/includes/internet_archive_queue.inc';

  //validate previous transfers
  internet_archive_validate_transfers();

  //Add new files to queue if available
  internet_archive_harvest_files();

  //transfer files available in the queue
  internet_archive_queue_drupal_queue_cron_run();

  //Check for new derivations to update.
  internet_archive_store_derivatives();
}

/**
 * Implements hook_theme().
 */
function internet_archive_theme() {
  return array(
    'queue_items' => array(
      'variables' => array('items' => NULL),
    ),
    'internet_archive_formatter_video_embed' => array(
      'variables' => array('file' => NULL),
    ),
    'internet_archive_formatter_thumbnail' => array(
      'variables' => array('file' => NULL),
    ),
    'internet_archive_formatter_animated_thumbnail' => array(
      'variables' => array('file' => NULL),
    ),
  );
}

/**
 * Theme function for the 'internet_archive_video_embed' formatter.
 */
function theme_internet_archive_formatter_video_embed($variables) {
  $element = $variables['file'];
  // Inside a View this function may be called with null data. In that case,
  // just return.
  if (empty($element['#item'])) {
    return '';
  }

  $field = content_fields($element['#field_name']);
  $item = $element['#item'];

  //TODO: may need to do some sanitization here..
  if ($item['value']) {
    $filepath = $item['value'];
  }
  else {
    // If there is no image on the database, use default.
    if (empty($item['fid']) && $field['use_default_file']) {
      $item = $field['default_file'];
    }
    if (empty($item['filepath']) && !empty($item['fid'])) {
      $item = array_merge($item, field_file_load($item['fid']));
    }

    $filepath = $item['filepath'];
  }

  return empty($filepath) ? '' :
    internet_archive_embed(file_create_path($filepath));
}

/**
 * Theme function for the 'internet_archive_video_thumbnail' formatter.
 */
function theme_internet_archive_formatter_thumbnail($variables) {
  $element = $variables['file'];
  // Inside a View this function may be called with null data. In that case,
  // just return.
  if (empty($element['#item'])) {
    return '';
  }

  $field = content_fields($element['#field_name']);
  $item = $element['#item'];

  //TODO: may need to do some sanitization here..
  if ($item['value']) {
    $filepath = $item['value'];
  }
  else {
    // If there is no image on the database, use default.
    if (empty($item['fid']) && $field['use_default_file']) {
      $item = $field['default_file'];
    }
    if (empty($item['filepath']) && !empty($item['fid'])) {
      $item = array_merge($item, field_file_load($item['fid']));
    }

    $filepath = $item['filepath'];
  }

  return empty($filepath) ? '' : '<img src="' .
    internet_archive_thumb_from_filepath(file_create_path($filepath)) . '" />';
}

/**
 * Theme function for the 'internet_archive_video_thumbnail' formatter.
 */
function theme_internet_archive_formatter_animated_thumbnail($variables) {
  $element = $variables['file'];
  // Inside a View this function may be called with null data. In that case,
  // just return.
  if (empty($element['#item'])) {
    return '';
  }

  $field = content_fields($element['#field_name']);
  $item = $element['#item'];

  //TODO: may need to do some sanitization here..
  if ($item['value']) {
    $filepath = $item['value'];
  }
  else {
    // If there is no image on the database, use default.
    if (empty($item['fid']) && $field['use_default_file']) {
      $item = $field['default_file'];
    }
    if (empty($item['filepath']) && !empty($item['fid'])) {
      $item = array_merge($item, field_file_load($item['fid']));
    }

    $filepath = $item['filepath'];
  }

  return empty($filepath) ? '' : '<img src="' .
    internet_archive_animated_thumb_from_filepath(file_create_path($filepath))
    . '" />';
}

/********************************************************
 * Metadata Integration
 ********************************************************
 */

/**
 * Builds an array of metadata by calling hook_internet_archive_metadata
 * TODO: Convert this to hook_internet_archive
 * @param $filepath
 *   A string containing a file path.
 *
 * @return $metadata
 *   An array of metadata keyed by header name
 */
function internet_archive_get_metadata($filepath) {
  dsm('internet_archive_get_metadata');
  $metadata = array();
  $node = internet_archive_get_node_from_filepath($filepath);

  $results = module_invoke_all('internet_archive_metadata', $node, $filepath);
  foreach ($results as $result) {
    $metadata = array_merge($result, $metadata);
  }

  //if mediatype is not set, try to figure it out manually
  //TODO: add a whole bunch more mimetype mappings to this list.
  if (!$metadata['mediatype']) {
    $pathinfo = pathinfo($filepath);
    $filemime = file_get_mimetype($filepath);
    dsm($filemime, 'filemime');
    switch ($filemime) {
      case 'image/jpeg':
        $metadata['mediatype'] = 'Image';
        break;
      case 'audio/mpeg':
        $metadata['mediatype'] = 'audio';
        break;
      case 'video/mp2p':
    case 'video/mp4':
      case 'video/quicktime':
      case 'video/x-flv':
        $metadata['mediatype'] = 'movies';
        break;
      default:
        if (variable_get('internet_archive_debug', FALSE)) {
          watchdog('internet_archive',
		   'Warning, no media type found. Defaulting to: ' .
		   variable_get('internet_archive_mediatype', 'movies'),
		   NULL, WATCHDOG_WARNING);
        }

        $metadata['mediatype'] = variable_get('internet_archive_mediatype',
					      'movies');
        break;
    }
  }

  //if no collection was specified in hook_internet_archive_metadata, check
  //for default in settings
  if (!$metadata['collection'] &&
      ($default_collection =
       variable_get('internet_archive_collection', "test_collection"))) {
    $metadata['collection'] = explode(',', $default_collection);
  }

  //if no title has been provided, and administrative setting is set item to
  //node title, set it now
  if (variable_get('internet_archive_bucket_title', FALSE) &&
      !$metadata['title'] && $node->title) {
    $metadata['title'] = $node->title;
  }
  elseif (!$metadata['title']) {
    //finally if no title has been provided, use the filename.
    $metadata['title'] = basename($filepath);
  }

  //if no description has been provided, and administrative setting is set
  ///description to body, set it now
  if (variable_get('internet_archive_bucket_body', FALSE) &&
      !$metadata['description'] && $node->body) {
    $metadata['description'] = $node->body;
  }

  //if no creative commons license has been provided, but it is available
  //in node, set it now
  if (!$metadata['licenseurl'] && $node->cc->uri) {
    $metadata['licenseurl'] = $node->cc->uri;
  }

  return $metadata;
}

/**
 * Builds archive.org compatible S3 header data.
 *
 * @param $metadata
 *   An array of metadata entries.
 *
 * @return $headers
 *   An array of headers.
 */
function internet_archive_process_metadata($metadata) {

  $headers = array();
  foreach ($metadata as $m_key => $info) {
    if (is_array($info)) {
      $counter = 1;
      foreach ($info as $i_key => $value) {
        $headers['x-amz-meta0' . $counter . '-' . $m_key] =
	  internet_archive_clean_text($value);
        $counter++;
      }
    }
    else {
      $headers['x-amz-meta-' . $m_key] = internet_archive_clean_text($info);
    }
  }

  return $headers;
}

/**
 * Cleans characters that break S3 from the header values.
 *
 * @param $string
 *   A string.
 *
 * @return $string
 *   A string without most html tags, whitespace, line breaks, tabs.
 */
function internet_archive_clean_text($string) {
  $string = strip_tags($string, '<a><br>');
  $string = trim($string);
  $string = str_replace(array("\r\n", "\r", "\n", "\t"), ' ', $string);

  return $string;
}

/**
 * Finds a node connected to a filepath based on the fields chosen
 * in the general settings.
 *
 * @param $filepath
 *   A string containing a file path.
 *
 * @return $node
 *   Drupal node object, or FALSE if nothing is found.
 */
function internet_archive_get_node_from_filepath($filepath) {
  dsm('internet_archive_get_node_from_filepath');
  $tables = internet_archive_get_field_tables();

  foreach ($tables as $key => $table_info) {

    switch ($table_info['type']) {
    case 'filefield':
    case 'text':
    case 'emvideo':
      drupal_set_message('Only the file field type is defined at this time',
			 'warning');
      return NULL;
      break;
    case 'file':
      $query =
	"SELECT entity_id FROM {" . $table_info['name'] . "} ft ".
	"INNER JOIN {file_managed} fm " .
	"ON ft." .$table_info['value_column'] .	" = fm.fid ".
	"WHERE fm.uri=:uri";
      
      $nid = db_query($query, array(':uri' => $filepath))->fetchField();

      if ($nid) {
	$node = node_load($nid);
	dsm($node, "found node from filepath: $filepath");
	return $node;
      }
      break;
    }
  }

  return FALSE;
}

/**
 * Gets field and node info from a filepath
 *
 * @param $filepath
 *   string, complete filepath
 * @return array
 *   an array containing a field_info array, and nid, or FALSE if nothing found
 */
function internet_archive_filepath_field_info($filepath) {
  dsm('internet_archive_filepath_field_info');
  $tables = internet_archive_get_field_tables();

  foreach ($tables as $key => $table_info) {

    switch ($table_info['type']) {
      case 'filefield':
        $query = "SELECT nid FROM {" . $table_info['name'] . "} JOIN {files} on " . $table_info['name'] . "." . $table_info['value_column'] . "=files.fid WHERE files.filepath='%s'";
        // TODO Please convert this statement to the D7 database API syntax.
        $nid = db_query($query, $filepath)->fetchField();
        if ($nid) {
          $info = array();
          $info['table_info'] = $table_info;
          $info['nid'] = $nid;
          return $info;
        }
        break;
      case 'text':
      case 'emvideo':
        $query = "SELECT nid FROM {" . $table_info['name'] . "} WHERE " . $table_info['name'] . "." . $table_info['value_column'] . "='%s'";
        // TODO Please convert this statement to the D7 database API syntax.
        $nid = db_query($query, $filepath)->fetchField();
        if ($nid) {
          $info = array();
          $info['table_info'] = $table_info;
          $info['nid'] = $nid;
          return $info;
        }
        break;
    }
  }

  return FALSE;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_thumb_from_filepath($key) {
  $data = internet_archive_load_data($key);

  if ((!$item = $data['item']) || $data['status'] != 'derived') {
    return FALSE;
  }

  $pathinfo = pathinfo($data['archive_url']);
  $filename = $pathinfo['filename'] . '_000001.jpg';

  $link = 'http://www.archive.org/download/';
  $link .= $item . '/' . $item . '.thumbs/';
  $link .= $filename;
  return $link;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_animated_thumb_from_filepath($key) {
  $data = internet_archive_load_data($key);

  if ((!$item = $data['item']) || $data['status'] != 'derived') {
    return FALSE;
  }

  $pathinfo = pathinfo($data['archive_url']);
  $filename = $pathinfo['filename'] . '.gif';

  $link = 'http://www.archive.org/download/';
  $link .= $item . '/';
  $link .= $filename;
  return $link;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_embed($key, $width = 470, $height = 371) {
  dsm("internet_archive_embed");
  $data = internet_archive_load_data($key);
  dsm($data, 'dataa');
  $url = internet_archive_derivative_url($data, 'mp4');
  dsm($url, 'url');
  if ($url) {
    $embed = internet_archive_create_embed($url, $width, $height);
  }
  else {
    return FALSE;
  }

  return $embed;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_derivative_url($item, $extension) {
  $derivatives = unserialize($item['derivatives']);
  if ($derivatives) {
    foreach ($derivatives as $key => $info) {
      $pathinfo = pathinfo($key);
      if ($pathinfo['extension'] == $extension) {
        $filename = $key;
      }
    }
  }

  if ($filename) {
    $url = 'http://www.archive.org/download/' . $item['item'] . '/' . $filename;
    return $url;
  }
  else {
    return FALSE;
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_create_embed($url, $width = 470, $height = 371) {
  dsm("internet_archive_create_embed");
  $embed = '';
  $pathinfo = pathinfo($url);
  dsm($pathinfo, 'path info');
  $base_url = $pathinfo['dirname'] . '/';
  $filename = $pathinfo['basename'];

  //$embed = '<object width="'.$width.'" height="'.$height.'"
  //classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">';
  $embed .= '<param value="true" name="allowfullscreen"/>';
  $embed .= '<param value="always" name="allowscriptaccess"/>';
  $embed .= '<param value="high" name="quality"/>';
  $embed .= '<param value="true" name="cachebusting"/>';
  $embed .= '<param value="#000000" name="bgcolor"/>';
  $embed .= '<param name="movie" ' .
    'value="http://www.archive.org/flow/flowplayer.commercial-3.2.1.swf" />';

  $embed .= "<param value=\"config={'key':'#\$aa4baff94a9bdcafce8','playlist':['format=Thumbnail?.jpg',{'autoPlay':false,'url':'" . $filename . "'}],'clip':{'autoPlay':true,'baseUrl':'" . $base_url . "','scaling':'fit','provider':'h264streaming'},'canvas':{'backgroundColor':'#000000','backgroundGradient':'none'},'plugins':{'controls':{'playlist':false,'fullscreen':true,'height':26,'backgroundColor':'#000000','autoHide':{'fullscreenOnly':true}},'h264streaming':{'url':'http://www.archive.org/flow/flowplayer.pseudostreaming-3.2.1.swf'}, 'sharing':{'url':'http://www.denveropenmedia.org/sites/all/plugins/flowplayer/flowplayer.sharing-3.2.1.swf'}},'contextMenu':[{},'-','Flowplayer v3.2.1']}\" name=\"flashvars\"/>";

  $embed .= '<embed src="http://www.archive.org/flow/flowplayer.commercial-3.2.1.swf" type="application/x-shockwave-flash" width="' . $width . '" height="' . $height . '" allowfullscreen="true" allowscriptaccess="always" cachebusting="true" bgcolor="#000000" quality="high" flashvars="config={\'key\':\'#$aa4baff94a9bdcafce8\',\'playlist\':[\'format=Thumbnail?.jpg\',{\'autoPlay\':false,\'url\':\'' . $filename . '\'}],\'clip\':{\'autoPlay\':true,\'baseUrl\':\'' . $base_url . '\',\'scaling\':\'fit\',\'provider\':\'h264streaming\'},\'canvas\':{\'backgroundColor\':\'#000000\',\'backgroundGradient\':\'none\'},\'plugins\':{\'controls\':{\'playlist\':false,\'fullscreen\':true,\'height\':26,\'backgroundColor\':\'#000000\',\'autoHide\':{\'fullscreenOnly\':true}},\'h264streaming\':{\'url\':\'http://www.archive.org/flow/flowplayer.pseudostreaming-3.2.1.swf\'}},\'contextMenu\':[{},\'-\',\'Flowplayer v3.2.1\']}"></embed>';
  //$embed .= '</object>';

  return $embed;
}

/**
 * Fetches all the cck tables associated with the fields defined in the
 * general settings area.
 *
 * @return $tables
 *   An array of table names
 */
function internet_archive_get_field_tables() {
  $fields = internet_archive_fields();

  foreach ($fields as $field_name => $field_info) {
    $extra = field_info_field($field_name);
    list($table, $table_info) =
      each($extra['storage']['details']['sql'][FIELD_LOAD_CURRENT]);
    
    //FIXME FIGURE OUT NEW WAY TO $db_info
    $db_info = array();
    switch ($field_info['type']) {
    case 'filefield':
    case 'text':
    case 'emvideo':
      $value_key = NULL;
      drupal_set_message('Only the file field type is defined at this time',
			 'warning');
      break;
    case 'file':
      $value_key = $table_info['fid'];
      
      break;
    }
    
    $tables[] = array(
      'name' => $table,
      'value_column' => $value_key,
      'type' => $field_info['type'],
    );
  }

  return $tables;
}

/**
 * Creates a safe bucket/item name from plain text.
 * TODO: I'm probably too greedy with the regex below, can preserve underscores and a few other chars.
 * @param $text
 *   A string containing text to make into an item name.
 *
 * @return
 *   Same text stripped of all non-alphanumeric characters
 */
function internet_archive_create_item_name($text) {
  dsm('internet_archive_create_item_name');
  $clean = preg_replace("/[^a-z0-9_-]+/i", "_", $text);
  $clean = substr($clean, 0, 60);
  return strtolower($clean);
}

/**
 * Fetches all data from the internet_archive table for a filepath
 *
 * @param $key
 *   A nid, or a string to original file path.
 *
 * @return $data
 *   An array of internet archive data, or FALSE if not found.
 */
function internet_archive_load_data($key) {
  dsm("internet_archive_load_data");
  if (is_numeric($key)) {
    $data = db_query("SELECT * from {internet_archive} WHERE tid = :tid",
		     array(':tid' => $key))->fetchAssoc();
    dsm($data, 'wtf');
    return $data;
  }
  else {
    $data=db_query("SELECT * from {internet_archive} WHERE in_path = :in_path",
		   array(':in_path' => $key))->fetchAssoc();
    return $data;
  }

  return FALSE;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_load_data_item($item) {
  $data = db_query("SELECT * FROM {internet_archive} WHERE item = :item",
		   array(':item' => $item))->fetchAssoc();
  return $data;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_load_data_tid($tid) {
  if (is_numeric($tid)) {
    $data = db_query("SELECT * from {internet_archive} WHERE tid = :tid", array(':tid' => $tid))->fetchAssoc();
    return $data;
  }

  return FALSE;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_validate_url($url) {
  dsm("internet_archive_validate_url");
  $headers = get_headers($url, 1);
  dsm($headers, 'headers');
  if ($headers[0] != 'HTTP/1.1 200 OK' && $headers[1] != 'HTTP/1.1 200 OK') {
    return FALSE;
  }
  else {
    return TRUE;
  }
}

/********************************************************
 * Textfield / Emfield Integration
 ********************************************************
 */

/**
 * Grabs a list of fields for use in a select list.
 *
 * @param $field_types
 *   An array of field types to select from.
 *
 * @return $possible_fields
 *   All fields that fit the specified field types.
 */
function internet_archive_field_select_options($field_types = array('filefield', 'text', 'emvideo', 'file', 'media')) {
  $fields = field_info_fields();
 
  $possible_fields = array();
  foreach ($fields as $field_name => $field) {
    if (in_array($field['type'], $field_types)) {
      $possible_fields[$field_name] = $field_name;
    }
  }
  asort($possible_fields);
  return $possible_fields;
}



/********************************************************
 * General Field Integration
 ********************************************************
 */
/**
 * Implements hook_field_formatter_info().
 */
function internet_archive_field_formatter_info() {
  return array(
    'video_embed' => array(
      'label' => t('Internet Archive Video Embed'),
      'field types' => array('file', 'filefield', 'text', 'emvideo'),
      'description' => t('Displays video embed code from archive.org.'),
    ),
    'thumbnail' => array(
      'label' => t('Internet Archive Thumbnail'),
      'field types' => array('file', 'filefield', 'text', 'emvideo'),
      'description' => t('Displays thumbnail from archive.org.'),
    ),
    'animated_thumbnail' => array(
      'label' => t('Internet Archive Animated Thumbnail'),
      'field types' => array('file', 'filefield', 'text', 'emvideo'),
      'description' => t('Displays animated thumbnail from archive.org.'),
    ),
  );
}

/********************************************************
 * Views Integration
 ********************************************************
 */

/**
 * Implements hook_views_api().
 * @return Array with Views API version.
 */
function internet_archive_views_api() {
  return array(
	       'api' => 3,
	       'path' => 
	       drupal_get_path('module', 
			       'internet_archive').'/includes'
	       );
}

/**
 * Implements hook_views_data().
 * @return Array with Views table information.
 */
function internet_archive_views_data() {
  $data['internet_archive']['table']['group'] = t('Internet Archive');

  $data['internet_archive']['table']['base'] = array(
    'field' => 'tid',
    'title' => t('Internet Archive'),
    'help' => t("Information regarding files transferred to Archive.org"),
    'weight' => -10,
  );

  $data['internet_archive']['table']['join'] = array(
    'node' => array(
      'left_field' => 'nid',
      'field' => 'nid',
    ),
  );

  $data['internet_archive']['tid'] = array(
    'title' => t('Transfer ID'),
    'help' => t('Numeric ID unique to each archive.org transfer'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
  );
  $data['internet_archive']['nid'] = array(
    'title' => t('Node ID'),
    'help' => t('Origin node of the file'), // The help that appears on the UI,
    // Information for displaying the nid
    'relationship' => array(
      'label' => t('Node'),
      'base' => 'node',
      'base field' => 'nid',
    ),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
  );
  $data['internet_archive']['in_path'] = array(
    'title' => t('Source Path'),
    'help' => t('Path to file transferred to archive.org'), // The help that appears on the UI,
    'relationship' => array(
      'label' => t('Files'),
      'base' => 'files',
      'base field' => 'filepath',
    ),
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );
  $data['internet_archive']['archive_url'] = array(
    'title' => t('Archive.org URL'),
    'help' => t('URL to file on Archive.org'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field_url',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );
  $data['internet_archive']['filename'] = array(
    'title' => t('Filename'),
    'help' => t('Source filename'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );
  $data['internet_archive']['md5'] = array(
    'title' => t('MD5 Hash'),
    'help' => t('MD5 Hash of the file sent to Archive.org'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );
  $data['internet_archive']['item'] = array(
    'title' => t('Item Identifier'),
    'help' => t('Item/Bucket name of the resource on archive.org'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );
  $data['internet_archive']['status'] = array(
    'title' => t('Transfer Status'),
    'help' => t('Status of the transfer to archive.org'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );
  $data['internet_archive']['date'] = array(
    'title' => t('Date Archived'),
    'help' => t('Date the transfer was initiated to archive.org'), // The help that appears on the UI,
    // Information for displaying the nid
    'field' => array(
      'handler' => 'views_handler_field_date',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_date',
    ),
  );
  return $data;
}

/** utility function, checks validated files to see if they have any derivatives, if not sets to failed **/
function internet_archive_repair_validated() {
  $result = db_query("SELECT * FROM {internet_archive} WHERE status = :status", array(':status' => ARCHIVE_VALIDATED));
  $total = 0;
  $failed_count = 0;
  while ($data = $result->fetchAssoc()) {
    $derivatives = internet_archive_get_derivatives($data['item']);
    if (!$derivatives) {
      // TODO Please review the conversion of this statement to the D7 database API syntax.
      /* db_query("UPDATE {internet_archive} SET status='%s', derivatives = null WHERE tid=%d", ARCHIVE_FAILED, $data['tid']) */
      db_update('internet_archive')
  ->fields(array(
        'status' => ARCHIVE_FAILED,
        'derivatives' => null,
      ))
  ->condition('tid', $data['tid'])
  ->execute();
      $failed_count++;
    }
    $total++;
  }

  drupal_set_message($failed_count . ' / ' . $total . ' have been marked as failed, with no derivatives available');
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_derivative_extensions() {
  $result = db_query("SELECT * FROM {internet_archive} ORDER BY tid DESC LIMIT 50");

  $extensions = array();
  while ($archive_info = $result->fetchAssoc()) {
    $derivatives = unserialize($archive_info['derivatives']);
    foreach ($derivatives as $key => $info) {
      $pathinfo = pathinfo($key);
      if (!$extensions[$pathinfo['extension']]) {
        $extensions[$pathinfo['extension']] = $info['name'];
      }
    }
  }

  return $extensions;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_tab_permission($node) {
  global $user;
  if (user_access('access all internet_archive node tabs') || (user_access('access own internet_archive node tabs') && $user->uid == $node->uid)) {
    if ($node_fields = internet_archive_node_fields($node)) {
      return TRUE;
    }
  }
  else {
    return FALSE;
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_node_status($node) {
  global $user;
  $files = internet_archive_node_files($node->nid);
  //$field_files = internet_archive_node_field_files($node);

  if (count($files) >= 1) {
    if (user_access('update all internet_archive metadata') || (user_access('update own internet_archive metadata') && $user->uid == $node->uid) || user_access('administer internet_archive')) {
      $operations .= l('Click here to update Metadata stored at Archive.org for this node', 'node/' . $node->nid . '/ia/update-metadata');
    }
    if ($operations) {
      $output .= '<div class="admin-panel">';
      $output .= '<br />';
      $output .= '<h3>Available Operations:</h3>';
      $output .= $operations;
      $output .= '<br /><br />';
      $output .= '</div>';
    }
  }

  if (count($files) >= 1) {
    $output .= '<div class="admin-panel">';
    $output .= '<h3>Files currently at Archive.org:</h3>';
    $output .= internet_archive_node_files_table($node);
    $output .= '</div>';

    if (user_access('access internet_archive logs')) {
      $output .= '<div class="admin-panel">';
      $output .= internet_archive_log_view('nid', $node->nid);
      $output .= '</div>';
    }
  }

  if (!$output) {
    $output .= 'There is currently no data stored at archive.org for this node.';
  }

  return $output;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_node_files_table($node) {
  global $user;
  $files = internet_archive_node_files($node->nid);

  if (count($files >= 1)) {
    $header = array(t('Filename'), t('Archive Page'), t('Status'));
    if (user_access('delete all internet_archive files') || (user_access('delete own internet_archive files') && $user->uid == $node->uid)) {
      $header[] = t('Delete files at Archive.org');
    }
    if (user_access('access internet_archive logs')) {
      $header[] = t('View log');
    }
    if (module_exists('internet_archive_download') && user_access('administer internet_archive')) {
      $header[] = t('Re-Queue Download');
    }

    foreach ($files as $key => $archive_info) {
      unset($row);
      if (strlen($archive_info['filename']) > 20) {
        $filename = substr($archive_info['filename'], 0, 20) . '...';
      }
      else {
        $filename = $archive_info['filename'];
      }
      $row = array(
        $filename,
        l('Visit', 'http://www.archive.org/details/' . $archive_info['item']),
        $archive_info['status'],
      );
      if (user_access('delete all internet_archive files') || (user_access('delete own internet_archive files') && $user->uid == $node->uid)) {
        $row[] = l('Delete', 'node/' . $node->nid . '/ia/delete-files/' . $archive_info['tid']);
      }
      if (user_access('access internet_archive logs')) {
        $row[] = l('Log', 'ia/log/' . $archive_info['tid']);
      }
      if (module_exists('internet_archive_download') && user_access('administer internet_archive')) {
        if ($archive_info['status'] == 'derived') {
          $row[] = l('Queue', 'ia/queue-download/' . $archive_info['tid']);
        }
      }

      $rows[] = $row;
    }

    return theme('table', array('header' => $header, 'rows' => $rows));
  }
  else {
    return t('No files from this node have been transferred to Archive.org');
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_node_fields($node) {
  $fields = internet_archive_fields();
  $node_fields = array();
  if ($fields) {
    foreach ($fields as $field_name => $info) {
      if ($node->{$field_name}) {
        $node_fields[] = $field_name;
      }
    }
  }

  if (count($node_fields >= 1)) {
    return $node_fields;
  }
  else {
    return FALSE;
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_node_field_files($node) {
  //grab all applicable fields
  $fields = internet_archive_fields();

  $field_files = array();

  foreach ($fields as $field_name => $field_info) {
    //get the value key to reference
    switch ($field_info['type']) {
    case 'filefield':
      $value_key = 'filepath';
      break;
    case 'text':
    case 'emvideo':
      $value_key = 'value';
      break;
    case 'file':
      $value_key = 'uri';
      break;
    }

    if ($node->$field_name) {
      if ($node->{$field_name}[0][$value_key]) {
        $field_files[] = array(
          'field_name' => $field_name,
          'value' => $node->{$field_name}[0][$value_key],
        );
      }
    }
  }

  if (count($field_files >= 1)) {
    return $field_files;
  }
  else {
    return FALSE;
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_update_node_metadata_permission($node) {
  global $user;
  if (user_access('update all internet_archive metadata') || (user_access('update own internet_archive metadata') && $user->uid == $node->uid)) {
    if ($files = internet_archive_node_files($node->nid)) {
      return TRUE;
    }
  }
  else {
    return FALSE;
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_update_node_metadata($node) {
  if ($files = internet_archive_node_files($node->nid)) {
    foreach ($files as $key => $archive_data) {
      internet_archive_update_item($archive_data['in_path']);
    }
    drupal_set_message('Metadata at Archive.org updated. <strong>Note that it may take some time for this update to be visible at Archive.org!</strong>');
    drupal_goto('node/' . $node->nid . '/ia');
  }
  else {
    drupal_set_message('No item found for this node at Archive.org!');
    drupal_goto('node/' . $node->nid . '/ia');
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_delete_node_files_permission($node) {
  global $user;
  if (user_access('delete all internet_archive files') || (user_access('delete own internet_archive files') && $user->uid == $node->uid)) {
    if ($files = internet_archive_node_files($node->nid)) {
      return TRUE;
    }
  }
  else {
    return FALSE;
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_delete_node_files($node, $tid) {
  if ($archive_data = internet_archive_load_data_tid($tid)) {
    internet_archive_delete_files($archive_data);

    db_delete('internet_archive')
      ->condition('tid', $tid)
      ->execute();
    $msg = t('Selected files at Archive.org deleted. <strong>Note that it '.
	     'may take some time for this update to be visible at '.
	     'Archive.org!</strong>');
	     
    drupal_set_message($msg);
    $log_entry = array(
      'tid' => $tid,
      'message' => t('File and derivatives deleted at Archive.org'),
      'message_data' => $archive_data,
      'type' => ARCHIVE_LOG_WARNING,
    );
    internet_archive_log($log_entry);
    drupal_goto('node/' . $node->nid . '/ia');
  }
  else {
    drupal_set_message('No files found for this source at Archive.org!');
    $log_entry = array(
      'tid' => $tid,
      'message' => t('No entries found for this file at Archive.org'),
      'message_data' => $archive_data,
      'type' => ARCHIVE_LOG_ERROR,
    );
    internet_archive_log($log_entry);
    drupal_goto('node/' . $node->nid . '/ia');
  }
}

/**
 * Log function used to record all updates associated with file transfers
 */
function internet_archive_log($data) {
  dsm($data, "Log entry!!!!!!!!!!!!!!!!!!!!!!!!!");
  if ($data['tid'] && $data['message'] && $data['type']) {
    // TODO Please review the conversion of this statement to the D7 database API syntax.
    /* db_query("INSERT INTO {internet_archive_log} (tid, message, message_data, type, date) VALUES (%d, '%s', '%s', %d, %d)", $data['tid'], $data['message'], serialize($data['message_data']), $data['type'], REQUEST_TIME) */
    $id = db_insert('internet_archive_log')
  ->fields(array(
      'tid' => $data['tid'],
      'message' => $data['message'],
      'message_data' => serialize($data['message_data']),
      'type' => $data['type'],
      'date' => REQUEST_TIME,
    ))
  ->execute();
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_log_table($type = 'tid', $identifier = NULL,
				    $show_only_errors_and_warnings = FALSE) {
  dsm('internet_archive_log_table');
  $args = array();
  switch ($type) {
    case 'tid':
      $where = ' WHERE log.tid=:tid';
      $args[':tid'] = $identifier;
      break;
    case 'nid':
      $where = ' WHERE archive.nid=:nid';
      $args[':nid'] = $identifier;
      break;
    case 'global':
      if ($show_only_errors_and_warnings) {
        $where = " WHERE log.type='" . ARCHIVE_LOG_WARNING .
	  "' OR log.type='" . ARCHIVE_LOG_ERROR . "'";
      }
      break;
  }

  $query =
    "SELECT log.lid, log.tid, log.message, log.message_data, log.type,".
    "log.date ".
    "FROM {internet_archive_log} AS log ".
    "INNER JOIN {internet_archive} AS archive ON archive.tid=log.tid" .
    $where . " ORDER BY log.date DESC";

  $page_number = arg(4);
  $results_per_page = variable_get('internet_archive_results_per_page', 100);

  if ($page_number && $page_number > 1) {
    $min = (($results_per_page) * $page_number) - $results_per_page;
  }
  else {
    $page_number = 1;
    $min = 0;
  }
  
  $result = db_query_range($query, $min, $results_per_page, $args);

  while ($log_entry = $result->fetchAssoc()) {
    switch ($log_entry['type']) {
      case 1:
        $friendly_type = 'error';
        break;
      case 2:
        $friendly_type = 'warning';
        break;
      case 3:
        $friendly_type = 'notice';
        break;
    }

    $message = $log_entry['message'];
    $message .= "&nbsp;on <em>" . date("F j, Y, g:i a", $log_entry['date']) .
      "</em>";

    if (function_exists('krumo') && php_sapi_name() != 'cli') {
      $message .= '<br />';
      $message .= krumo_ob(unserialize($log_entry['message_data']));
    }

    $rows[] = array('data' => array(array('data'=>$message,
					  'class'=>array('')),
				    array('data'=>$friendly_type,
					  'class'=>array('ia-type')),
				    ),
		    'class' => array('ia-' . $friendly_type),
		    );
    
  }

  if (count($rows) > 0) {
    $header = array('Message', 'Type');

    $table = theme('table', array('header' => $header, 'rows' => $rows));

    if (!function_exists('krumo') || php_sapi_name() == 'cli') {
      $table .=
	t('For more detailed debugging, please install the devel module and '.
	  'return to this page.');
    }

    if ($page_number > 1) {
      $prev_page = $page_number - 1;
      $table .= "<br/>" .l("<<<<< Previous ",
			   "admin/reports/internet_archive/log/" . $prev_page);
      
      $table .= "&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
    }
    
    if (count($rows) == $results_per_page) {
      $next_page = $page_number + 1;
      $table .= l(" Next >>>>>>", "admin/reports/internet_archive/log/".
		  $next_page);
    }
    
    return $table;
  }
  else {
    $prev_page = $page_number - 1;
    $link .= "<br/>" .l("<<<<< Previous ",
			"admin/reports/internet_archive/log/" . $prev_page);

    return t('No log information is currently available for this file.').$link;
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_log_view($type = 'tid', $identifier = NULL) {
  dsm('internet_archive_log_view');

  if (user_access('access internet_archive logs')) {
    drupal_add_css(drupal_get_path('module', 'internet_archive') .
		   '/css/log.css');
    if ($type == 'tid') {
      $item = internet_archive_load_data_tid($identifier);
      $node = node_load($item['nid']);
      $output = '<br /><h3>Log for <i>' . $node->title . '</i> source file: ' .
	$item['in_path'] . '</h3>';

      $output .=
	l('Visit the node associated with this transfer',
	  'node/' . $item['nid'] . '/ia');
      
      $output .= ' | ' . l('View the main log page',
			   'admin/reports/internet_archive/log');
    }
    elseif ($type == 'nid') {
      $node = node_load($identifier);
      $output =
	'<h3>Combined log for all transfers associated with the '.
	'<i>' . $node->title . '</i> node</h3>';
    }
    elseif ($type == 'global') {
      $output = '<h3>Global message log</h3>';
    }

    $show_notice_config =
      variable_get('internet_archive_show_only_errors_and_warnings', FALSE);

    if (arg(3) == 'log' && $show_notice_config) {
      $show_only_errors_and_warnings = TRUE;
    }
    else {
      $show_only_errors_and_warnings = FALSE;
    }
    
    $output .= internet_archive_log_table($type, $identifier,
					  $show_only_errors_and_warnings);
    
    return $output;
  }
  else {
    drupal_access_denied();
  }

}

/**
 * Workaround for PHPs lame 2GB/4GB filesize issues
 * Created with help from Ray Tiley, http://groups.drupal.org/user/81206
 */
function internet_archive_filesize($file) {
  $size = filesize($file);

  //Try to accomodate 32bit environments that allow shell command execution and have ls
  //Theoretically PHP will always return a negative or 0 value if it cannot handle the large filesize
  //Who knows what Windows does.
  if ($size < 0 || $size == 0) {
    $cmd = "ls -l " . escapeshellarg($file) . " | awk '{print $5}'";
    $ls_size = $cmd;
    if (is_numeric(trim($ls_size))) {
      $size = $ls_size;
    }
  }

  return $size;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_seconds_hhmmss($seconds) {
  $days = floor($seconds / 86400);
  $days_mod = $seconds % 86400;
  $hours = floor($days_mod / 3600);
  $hours_mod = $days_mod % 3600;
  $minutes = floor($hours_mod / 60);
  $minutes_mod = $hours_mod % 60;
  $seconds = floor($minutes_mod);

  if ($hours < 10) {
    $hours = '0' . $hours;
  }
  if ($minutes < 10) {
    $minutes = '0' . $minutes;
  }
  if ($seconds < 10) {
    $seconds = '0' . $seconds;
  }

  $formatted = $hours . ':' . $minutes . ':' . $seconds;
  return $formatted;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function internet_archive_help_links($name, $type = 'icon') {
  switch ($type) {
    case 'icon':
      // TODO Please change this theme call to use an associative array
      //for the $variables parameter.
      $output = theme('advanced_help_topic', 'internet_archive', $name);
      break;
    case 'link':
      // TODO Please change this theme call to use an associative array for
      //the $variables parameter.
      $link = theme('advanced_help_topic', 'internet_archive', $name, 'title');
      if (!$link) {
        $link = t('Please install the ') .
	  l('advanced help module', 'http://drupal.org/project/advanced_help')
	  . t(' for better documentation on using this module.');
      }
      else {
        $link = t('Help on the: !link.', array('!link' => $link));
      }
      $output = $link;
      break;
    case 'text':
      $output = t('Click the ? icon above for more help on this page.');
      break;
    case 'full':
      // TODO Please change this theme call to use an associative array for
      //the $variables parameter.
      $output = theme('advanced_help_topic', 'internet_archive', $name);
      $output .= '&nbsp;' .
	t('Click the help icon to view more details on this page.');
      break;
  }

  return $output;
}

/** * Implementation of hook_cron_queue_info() */
function internet_archive_cron_queue_info() {
  dsm("hi dad");
  // This is the callback function for each queue item.
  $queues['internet_archive_send_file'] =
    array(
	  'worker callback' => 'internet_archive_send_file_run',
	  'time' => 180, 
	  );
  return $queues;
}

function internet_archive_send_file_run($item) {
  dsm('internet_archive_send_file_run');
  global $internet_archive_queue_count;

  $internet_archive_queue_count = $internet_archive_queue_count ?
    $internet_archive_queue_count : 0;

  $internet_archive_queue_count ++;

  dsm($internet_archive_queue_count, 'my count');

  $limit = variable_get('internet_archive_queue_limit', '1');

  if ($internet_archive_queue_count > $limit) {
    throw new Exception('Item will remain in the queue.');
  }

  //FETCH DAYS OF WEEK AND CHECK
  if (!internet_archive_day_check()) {
    throw new Exception('Item will remain in the queue.');
  }
  
  //FETCH HOUR OF DAY AND CHECK
  if (!internet_archive_hour_check()) {
    throw new Exception('Item will remain in the queue.');
  }

  dsm($item, 'item');
  internet_archive_default_send($item);
  
}

/**
 * implements hook_action_info()
 */
function internet_archive_action_info() {
  $items = array();
    $items['internet_archive_delete_archive_item_action'] =
    array(
	  'type' => 'entity',
	  'label' =>
	  t('Internet Archive Transfers: Delete files, buckets, and items'),
	  'configurable' => FALSE,
	  'vbo_configurable' => FALSE,
	  'triggers' => array('any'),
	  'behavior' => array(),
	  );

  $items['internet_archive_complete_transfer_action'] =
    array(
	  'type' => 'entity',
	  'label' =>
	  t('Internet Archive Transfers: Validate and get Derivatives'),
	  'configurable' => FALSE,
	  'vbo_configurable' => FALSE,
	  'triggers' => array('any'),
	  'behavior' => array(),
	  );

  
  return $items;
}

/**
 * Custom VBO action callback function
 */
function internet_archive_complete_transfer_action(&$node, $context) {
  internet_archive_validate_transfers($node->nid);

  internet_archive_store_derivatives($node->nid);
}
/**
 * Custom VBO action callback function
 */
function internet_archive_delete_archive_item_action(&$node, $context){
  dsm($node, 'internet_archive_delete_archive_item_action');

  $sql = "SELECT * from {internet_archive} where nid = :nid";
  $results = db_query($sql, array(':nid' => $node->nid));

  while($result = $results->fetchAssoc()) {
    $archive_data = internet_archive_load_data_tid($result['tid']);
    dsm($archive_data, 'woohoo archive data');
    internet_archive_delete_files($archive_data);
    internet_archive_delete_item($archive_data);

    db_delete('internet_archive')
      ->condition('tid', $archive_data['tid'])
      ->execute();

    $msg = t('Selected files at Archive.org deleted. <strong>Note that it '.
	     'may take some time for this update to be visible at '.
	     'Archive.org!</strong>');
	     
    drupal_set_message($msg);
    $log_entry = array(
      'tid' => $tid,
      'message' => t('File and derivatives deleted at Archive.org'),
      'message_data' => $archive_data,
      'type' => ARCHIVE_LOG_WARNING,
    );
    internet_archive_log($log_entry);

  }
  
}
/**
 * implements hook_form_alter()
 */
function internet_archive_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-internet-archive-transfers-page') {
    $options = array(
		     '' => '<select>',
		     ARCHIVE_QUEUED => ARCHIVE_QUEUED,
		     ARCHIVE_TRANSFERRING => ARCHIVE_TRANSFERRING,
		     ARCHIVE_TRANSFERRED => ARCHIVE_TRANSFERRED,
		     ARCHIVE_VALIDATED => ARCHIVE_VALIDATED,
		     ARCHIVE_DERIVED => ARCHIVE_DERIVED,
		     ARCHIVE_DELETED => ARCHIVE_DELETED,
		     ARCHIVE_FAILED => ARCHIVE_FAILED,
		     );

    $form['status_1'] =
      array(
	    '#type' => 'select',
	    '#options' => $options,
	  );


  }
}